import 'package:flutter_test/flutter_test.dart';
import 'package:eatsbeats/models/daw_state.dart';
import 'package:eatsbeats/lua/default_song.dart';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  test('Song loading, playback, stop, and reloading transition roundtrip stability test', () async {
    final dawState = DawState();

    const midnightBitesSong = r'''
-- Eatsbeats Song File: "Midnight Bites"
-- Generated by Eatsbeats DAW

return eatsbeats.song {
  version = "1.0",
  meta = {
    title = "Midnight Bites",
    author = "Eatsbits",
    songKey = "C Major",
    bpm = 124.00,
    masterVolume = 0.85,
    isSongMode = false,
    isLooping = true,
    loopStartBar = 0,
    loopEndBar = 2,
  },

  patterns = {
    {
      id = "p0",
      name = "Pattern A",
      lengthSteps = 16,
      tracks = {
        {
          id = "t_kick",
          name = "Analog 909 Kick",
          color = 0xffff007a,
          type = "luaScript",
          volume = 0.950,
          pan = 0.000,
          isMuted = false,
          isSoloed = false,
          chordFollowMode = "off",
          sampleName = "kick",
          synthWaveform = "sawtooth",
          cutoff = 3000.0,
          resonance = 1.00,
          attack = 0.010,
          release = 0.300,
          trackerColumns = 4,
          activeView = "pianoRoll",
          luaScriptCode = [[
-- @name: Analog 909 Kick
-- @category: instrument
local Analog909Kick = {}
function Analog909Kick.init() end
function Analog909Kick.process(time, freq, note, params) return 0.0 end
return Analog909Kick
          ]],
          luaParams = {},
          steps = {},
          notes = {},
          clips = {},
          fxRack = {},
        },
        {
          id = "t_lua_303",
          name = "Eats-303",
          color = 0xff00ff66,
          type = "luaScript",
          volume = 0.900,
          pan = 0.000,
          isMuted = false,
          isSoloed = false,
          chordFollowMode = "off",
          sampleName = "kick",
          synthWaveform = "sawtooth",
          cutoff = 3000.0,
          resonance = 1.00,
          attack = 0.010,
          release = 0.300,
          trackerColumns = 4,
          activeView = "pianoRoll",
          luaScriptCode = [[
-- @name: Eats-303
-- @category: instrument
local Eats303 = {}
function Eats303.init()
  Param.add("Cutoff", 200.0, 4500.0, 1400.0)
  Param.add("Resonance", 0.5, 16.0, 9.2)
  Param.add("Slide", 0.0, 1.0, 0.8)
end
function Eats303.process(time, freq, note, params) return 0.0 end
return Eats303
          ]],
          luaParams = {
            ["Cutoff"] = 268.0808,
            ["Resonance"] = 15.2148,
            ["Slide"] = 0.8070,
          },
          steps = {},
          notes = {},
          clips = {
            {
              id = "c_w1",
              name = "Acid 303 Riff",
              trackId = "t_lua_303",
              startBar = 0,
              barLength = 2,
              notes = [
                { id = "n1", pitch = 24, startStep = 0.00, durationSteps = 4.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "n2", pitch = 36, startStep = 5.00, durationSteps = 1.00, velocity = 0.85, column = 0, effectCommand = "00", isSlide = true, isAccent = true },
                { id = "n3", pitch = 42, startStep = 8.00, durationSteps = 2.00, velocity = 0.85, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
              ],
            },
          },
          fxRack = [],
        },
      },
    },
  },
}
''';

    // 1. Load Midnight Bites
    dawState.loadFromEatsLua(midnightBitesSong);
    expect(dawState.projectName, 'Midnight Bites');

    // 2. Play pattern
    dawState.togglePlay();
    expect(dawState.isPlaying, isTrue);

    // Trigger notes
    final track303 = dawState.activePattern.tracks[1];
    dawState.audioEngine.playNoteOrSample(
      track: track303,
      midiNote: 36,
      velocity: 0.9,
      durationSec: 0.5,
      isSlide: true,
      targetMidiNote: 42,
    );

    // 3. Stop
    dawState.stop();
    expect(dawState.isPlaying, isFalse);

    // 4. Load a different song (e.g. DefaultSong)
    dawState.loadFromEatsLua(DefaultSong.midnightBitesLua);
    expect(dawState.patterns.isNotEmpty, isTrue);

    // 5. Play again
    dawState.togglePlay();
    expect(dawState.isPlaying, isTrue);
    dawState.stop();

    // 6. Reload Midnight Bites again
    dawState.loadFromEatsLua(midnightBitesSong);
    expect(dawState.projectName, 'Midnight Bites');
  });
}
