class DefaultSong {
  static const String midnightBitesLua = r'''-- Eatsbits Song File: "Midnight Bites"
-- Generated by Eatsbits DAW

return eatsbits.song {
  version = "1.0",
  meta = {
    title = "Midnight Bites",
    author = "Eatsbits",
    bpm = 124.00,
    masterVolume = 0.85,
    isSongMode = false,
    isLooping = true,
    loopStartBar = 0,
    loopEndBar = 2,
  },

  patterns = {
    {
      id = "p0",
      name = "Pattern A",
      lengthSteps = 16,
      tracks = {
        {
          id = "t_kick",
          name = "Eats Kick",
          color = 0xffff007a,
          type = "luaScript",
          volume = 0.950,
          pan = 0.000,
          isMuted = false,
          isSoloed = false,
          sampleName = "kick",
          synthWaveform = "sawtooth",
          cutoff = 3000.0,
          resonance = 1.00,
          attack = 0.010,
          release = 0.300,
          trackerColumns = 4,
          activeView = "pianoRoll",
          luaScriptCode = [[
-- --- Procedural Sub Kick Drum Script (Lua) ---
local ProceduralKick = {}

function ProceduralKick.init()
  Param.add("StartFreq", 100.0, 300.0, 160.0)
  Param.add("EndFreq", 30.0, 60.0, 42.0)
  Param.add("PitchDecay", 0.01, 0.2, 0.035)
  Param.add("AmpDecay", 0.05, 4.0, 0.35)
  Param.add("Click", 0.0, 1.0, 0.0)
end

function ProceduralKick.process(time, freq, note, params)
  local startF = params["StartFreq"] or 160.0
  local endF = params["EndFreq"] or 42.0
  local pDecay = params["PitchDecay"] or 0.035
  local aDecay = params["AmpDecay"] or 0.35
  local click = params["Click"] or 0.0

  -- Pitch sweep envelope
  local curFreq = endF + (startF - endF) * math.exp(-time / math.max(0.005, pDecay))
  local phase = 2.0 * math.pi * curFreq * time
  local subSine = math.sin(phase)

  -- Transient click
  local clickTransient = (math.random() * 2.0 - 1.0) * math.exp(-time * 150.0) * click

  -- Amplitude envelope decaying cleanly
  local env = math.exp(-time * 4.0 / math.max(0.01, aDecay))
  local rawOutput = (subSine * 0.85 + clickTransient * 0.15) * env

  -- Smooth fade toward edge of kick duration to guarantee clean drop to silence
  local maxDur = math.max(0.1, aDecay)
  local fadeStart = maxDur - 0.04
  local edgeFade = 1.0
  if time > fadeStart then
    local norm = math.max(0.0, math.min(1.0, (maxDur - time) / 0.04))
    edgeFade = 0.5 * (1.0 - math.cos(math.pi * norm))
  end
  if time >= maxDur then edgeFade = 0.0 end
  return math.tanh(rawOutput * edgeFade * 1.3)
end

return ProceduralKick

          ]],
          luaParams = {
            ["StartFreq"] = 120.1709,
            ["EndFreq"] = 56.3730,
            ["PitchDecay"] = 0.0311,
            ["AmpDecay"] = 0.6000,
            ["Click"] = 0.0000,
          },
          steps = {
            [1] = { pitch = 36, velocity = 0.95, isSlide = false, isAccent = true },
            [5] = { pitch = 36, velocity = 0.95, isSlide = false, isAccent = true },
            [9] = { pitch = 36, velocity = 0.95, isSlide = false, isAccent = true },
            [13] = { pitch = 36, velocity = 0.95, isSlide = false, isAccent = true },
            [17] = { pitch = 36, velocity = 0.95, isSlide = false, isAccent = true },
            [21] = { pitch = 36, velocity = 0.95, isSlide = false, isAccent = true },
            [25] = { pitch = 36, velocity = 0.95, isSlide = false, isAccent = true },
            [29] = { pitch = 36, velocity = 0.95, isSlide = false, isAccent = true },
          },
          notes = {
            { id = "k_0", pitch = 36, startStep = 0.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "k_4", pitch = 36, startStep = 4.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "k_8", pitch = 36, startStep = 8.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "k_12", pitch = 36, startStep = 12.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "k_16", pitch = 36, startStep = 16.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "k_20", pitch = 36, startStep = 20.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "k_24", pitch = 36, startStep = 24.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "k_28", pitch = 36, startStep = 28.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
          },
          clips = {
            {
              id = "c_k1",
              name = "Kick Beat A",
              trackId = "t_kick",
              startBar = 0,
              barLength = 4,
              notes = {
                { id = "k_0", pitch = 36, startStep = 0.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "k_4", pitch = 36, startStep = 4.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "k_8", pitch = 36, startStep = 8.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "k_12", pitch = 36, startStep = 12.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "k_16", pitch = 36, startStep = 16.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "k_20", pitch = 36, startStep = 20.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "k_24", pitch = 36, startStep = 24.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "k_28", pitch = 36, startStep = 28.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
              },
            },
          },
          fxRack = {
            { id = "fx_td", name = "TubeDistortion", type = "distortion", enabled = true, mix = 0.50, params = { ["Drive"] = 6.0000, ["OutGain"] = 0.7000 } },
          },
        },
        {
          id = "t_snare",
          name = "Eats Snare",
          color = 0xffff8c00,
          type = "luaScript",
          volume = 0.850,
          pan = 0.000,
          isMuted = false,
          isSoloed = false,
          sampleName = "kick",
          synthWaveform = "sawtooth",
          cutoff = 3000.0,
          resonance = 1.00,
          attack = 0.010,
          release = 0.300,
          trackerColumns = 4,
          activeView = "pianoRoll",
          luaScriptCode = [[
-- --- Procedural Snare Drum Script (Lua) ---
local ProceduralSnare = {}

function ProceduralSnare.init()
  Param.add("ToneFreq", 100.0, 320.0, 185.0)
  Param.add("Snappy", 0.0, 1.0, 0.65)
  Param.add("Decay", 0.05, 0.8, 0.18)
  Param.add("Variation", 0.0, 1.0, 0.0)
end

function ProceduralSnare.process(time, freq, note, params)
  local toneFreq = params["ToneFreq"] or 185.0
  local snappy = params["Snappy"] or 0.65
  local decay = params["Decay"] or 0.18
  local variation = params["Variation"] or 0.0

  if variation > 0.001 then
    local vOffset = (math.sin(note * 12.9898) * 0.5 + 0.5) * variation
    toneFreq = toneFreq * (1.0 + (vOffset - 0.5 * variation) * 0.08)
    decay = decay * (1.0 + (vOffset - 0.5 * variation) * 0.15)
  end

  local sweepFreq = toneFreq * (1.0 + 1.2 * math.exp(-time * 60.0))
  local body = math.sin(2.0 * math.pi * sweepFreq * time) * math.exp(-time * 22.0)
  local overtone = math.sin(2.0 * math.pi * (toneFreq * 1.75) * time) * math.exp(-time * 30.0) * 0.35
  local tonalCore = body + overtone

  local noise = (math.random() * 2.0 - 1.0) * math.exp(-time / math.max(0.01, decay))
  local filteredNoise = DSP.highpass(noise, 1800.0, 1.2)

  local click = (math.random() * 2.0 - 1.0) * math.exp(-time * 250.0) * 0.25

  local output = (tonalCore * (1.0 - snappy * 0.6) + filteredNoise * (snappy * 1.2) + click)
  return math.tanh(output * 1.3)
end

return ProceduralSnare

          ]],
          luaParams = {
            ["ToneFreq"] = 300.0000,
            ["Snappy"] = 0.1201,
            ["Decay"] = 0.0500,
          },
          steps = {
            [5] = { pitch = 38, velocity = 0.90, isSlide = false, isAccent = true },
            [13] = { pitch = 38, velocity = 0.90, isSlide = false, isAccent = true },
            [21] = { pitch = 38, velocity = 0.90, isSlide = false, isAccent = true },
            [29] = { pitch = 38, velocity = 0.90, isSlide = false, isAccent = true },
          },
          notes = {
            { id = "s_4", pitch = 38, startStep = 4.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "s_12", pitch = 38, startStep = 12.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "s_20", pitch = 38, startStep = 20.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "s_28", pitch = 38, startStep = 28.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
          },
          clips = {
            {
              id = "c_s1",
              name = "Snare Pattern",
              trackId = "t_snare",
              startBar = 0,
              barLength = 4,
              notes = {
                { id = "s_4", pitch = 38, startStep = 4.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "s_12", pitch = 38, startStep = 12.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "s_20", pitch = 38, startStep = 20.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "s_28", pitch = 38, startStep = 28.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
              },
            },
          },
          fxRack = {
            { id = "fx_td", name = "TubeDistortion", type = "distortion", enabled = true, mix = 0.50, params = { ["Drive"] = 6.0000, ["OutGain"] = 0.7000 } },
          },
        },
        {
          id = "t_hihat",
          name = "Eats Hats",
          color = 0xffffb700,
          type = "luaScript",
          volume = 0.750,
          pan = 0.000,
          isMuted = false,
          isSoloed = false,
          sampleName = "kick",
          synthWaveform = "sawtooth",
          cutoff = 3000.0,
          resonance = 1.00,
          attack = 0.010,
          release = 0.300,
          trackerColumns = 4,
          activeView = "pianoRoll",
          luaScriptCode = [[
-- --- Procedural Hi-Hat Synth Script (Lua) ---
local ProceduralHiHat = {}

function ProceduralHiHat.init()
  Param.add("Cutoff", 3000.0, 14000.0, 7500.0)
  Param.add("Decay", 0.01, 0.6, 0.06)
  Param.add("Metallic", 0.0, 1.0, 0.15)
  Param.add("Variation", 0.0, 1.0, 0.0)
end

function ProceduralHiHat.process(time, freq, note, params)
  local cutoff = params["Cutoff"] or 7500.0
  local decay = params["Decay"] or 0.06
  local metallic = params["Metallic"] or 0.15
  local variation = params["Variation"] or 0.0

  if variation > 0.001 then
    local vOffset = (math.sin(note * 78.233) * 0.5 + 0.5) * variation
    cutoff = cutoff * (1.0 + (vOffset - 0.5 * variation) * 0.12)
    decay = decay * (1.0 + (vOffset - 0.5 * variation) * 0.18)
  end

  local env = math.exp(-time / math.max(0.005, decay))

  local ring1 = math.sin(2.0 * math.pi * 320.0 * time)
  local ring2 = math.sin(2.0 * math.pi * 540.0 * time)
  local ring3 = math.sin(2.0 * math.pi * 890.0 * time)
  local metallicRing = (ring1 + ring2 + ring3) * 0.333

  local noise = (math.random() * 2.0 - 1.0)
  local rawSignal = noise * (1.0 - metallic * 0.3) + metallicRing * (metallic * 0.3)
  local filtered = DSP.highpass(rawSignal, cutoff, 1.4)

  return math.tanh(filtered * env * 1.1)
end

return ProceduralHiHat

          ]],
          luaParams = {
            ["Cutoff"] = 4051.2821,
            ["Decay"] = 0.0156,
            ["Metallic"] = 1.0000,
          },
          steps = {
            [1] = { pitch = 42, velocity = 0.60, isSlide = false, isAccent = false },
            [3] = { pitch = 42, velocity = 0.90, isSlide = false, isAccent = true },
            [5] = { pitch = 42, velocity = 0.60, isSlide = false, isAccent = false },
            [7] = { pitch = 42, velocity = 0.90, isSlide = false, isAccent = true },
            [9] = { pitch = 42, velocity = 0.60, isSlide = false, isAccent = false },
            [11] = { pitch = 42, velocity = 0.90, isSlide = false, isAccent = true },
            [13] = { pitch = 42, velocity = 0.60, isSlide = false, isAccent = false },
            [15] = { pitch = 42, velocity = 0.90, isSlide = false, isAccent = true },
            [17] = { pitch = 42, velocity = 0.60, isSlide = false, isAccent = false },
            [19] = { pitch = 42, velocity = 0.90, isSlide = false, isAccent = true },
            [21] = { pitch = 42, velocity = 0.60, isSlide = false, isAccent = false },
            [23] = { pitch = 42, velocity = 0.90, isSlide = false, isAccent = true },
            [25] = { pitch = 42, velocity = 0.60, isSlide = false, isAccent = false },
            [27] = { pitch = 42, velocity = 0.90, isSlide = false, isAccent = true },
            [29] = { pitch = 42, velocity = 0.60, isSlide = false, isAccent = false },
            [31] = { pitch = 42, velocity = 0.90, isSlide = false, isAccent = true },
          },
          notes = {
            { id = "h_0", pitch = 42, startStep = 0.00, durationSteps = 1.00, velocity = 0.60, column = 0, effectCommand = "00", isSlide = false, isAccent = false },
            { id = "h_2", pitch = 42, startStep = 2.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "h_4", pitch = 42, startStep = 4.00, durationSteps = 1.00, velocity = 0.60, column = 0, effectCommand = "00", isSlide = false, isAccent = false },
            { id = "h_6", pitch = 42, startStep = 6.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "h_8", pitch = 42, startStep = 8.00, durationSteps = 1.00, velocity = 0.60, column = 0, effectCommand = "00", isSlide = false, isAccent = false },
            { id = "h_10", pitch = 42, startStep = 10.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "h_12", pitch = 42, startStep = 12.00, durationSteps = 1.00, velocity = 0.60, column = 0, effectCommand = "00", isSlide = false, isAccent = false },
            { id = "h_14", pitch = 42, startStep = 14.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "h_16", pitch = 42, startStep = 16.00, durationSteps = 1.00, velocity = 0.60, column = 0, effectCommand = "00", isSlide = false, isAccent = false },
            { id = "h_18", pitch = 42, startStep = 18.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "h_20", pitch = 42, startStep = 20.00, durationSteps = 1.00, velocity = 0.60, column = 0, effectCommand = "00", isSlide = false, isAccent = false },
            { id = "h_22", pitch = 42, startStep = 22.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "h_24", pitch = 42, startStep = 24.00, durationSteps = 1.00, velocity = 0.60, column = 0, effectCommand = "00", isSlide = false, isAccent = false },
            { id = "h_26", pitch = 42, startStep = 26.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "h_28", pitch = 42, startStep = 28.00, durationSteps = 1.00, velocity = 0.60, column = 0, effectCommand = "00", isSlide = false, isAccent = false },
            { id = "h_30", pitch = 42, startStep = 30.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
          },
          clips = {
            {
              id = "c_h1",
              name = "Hi-Hat Groove",
              trackId = "t_hihat",
              startBar = 0,
              barLength = 4,
              notes = {
                { id = "h_0", pitch = 42, startStep = 0.00, durationSteps = 1.00, velocity = 0.60, column = 0, effectCommand = "00", isSlide = false, isAccent = false },
                { id = "h_2", pitch = 42, startStep = 2.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "h_4", pitch = 42, startStep = 4.00, durationSteps = 1.00, velocity = 0.60, column = 0, effectCommand = "00", isSlide = false, isAccent = false },
                { id = "h_6", pitch = 42, startStep = 6.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "h_8", pitch = 42, startStep = 8.00, durationSteps = 1.00, velocity = 0.60, column = 0, effectCommand = "00", isSlide = false, isAccent = false },
                { id = "h_10", pitch = 42, startStep = 10.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "h_12", pitch = 42, startStep = 12.00, durationSteps = 1.00, velocity = 0.60, column = 0, effectCommand = "00", isSlide = false, isAccent = false },
                { id = "h_14", pitch = 42, startStep = 14.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "h_16", pitch = 42, startStep = 16.00, durationSteps = 1.00, velocity = 0.60, column = 0, effectCommand = "00", isSlide = false, isAccent = false },
                { id = "h_18", pitch = 42, startStep = 18.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "h_20", pitch = 42, startStep = 20.00, durationSteps = 1.00, velocity = 0.60, column = 0, effectCommand = "00", isSlide = false, isAccent = false },
                { id = "h_22", pitch = 42, startStep = 22.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "h_24", pitch = 42, startStep = 24.00, durationSteps = 1.00, velocity = 0.60, column = 0, effectCommand = "00", isSlide = false, isAccent = false },
                { id = "h_26", pitch = 42, startStep = 26.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "h_28", pitch = 42, startStep = 28.00, durationSteps = 1.00, velocity = 0.60, column = 0, effectCommand = "00", isSlide = false, isAccent = false },
                { id = "h_30", pitch = 42, startStep = 30.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
              },
            },
          },
        },
        {
          id = "t_lua_303",
          name = "Eats-303",
          color = 0xff00ff66,
          type = "luaScript",
          volume = 0.900,
          pan = 0.000,
          isMuted = false,
          isSoloed = false,
          sampleName = "kick",
          synthWaveform = "sawtooth",
          cutoff = 3000.0,
          resonance = 1.00,
          attack = 0.010,
          release = 0.300,
          trackerColumns = 4,
          activeView = "pianoRoll",
          luaScriptCode = [[
-- --- Eats-303 Acid Bassline (JC-303 & Open303 DSP) ---
local Eats303 = {}

function Eats303.init()
  Param.add("Waveform", 0.0, 1.0, 0.0, 1.0)       -- 0 = Saw, 1 = Square
  Param.add("Pitch", -12.0, 12.0, 0.0, 1.0)       -- Tuning semitones
  Param.add("Cutoff", 200.0, 4500.0, 1400.0)      -- Base VCF Cutoff
  Param.add("Resonance", 0.5, 16.0, 9.2)          -- Diode Ladder Q with 150Hz Feedback HPF
  Param.add("EnvMod", 0.0, 1.0, 0.75)             -- Exponential VCF Envelope Sweep
  Param.add("Decay", 0.05, 1.2, 0.28)             -- Non-accented Decay (forced 200ms on Accent)
  Param.add("Accent", 0.0, 1.0, 0.78)             -- Accent Cutoff Pulse & Gain Boost
  Param.add("Octave", -2.0, 0.0, 0.0, 1.0)        -- Octave Transpose (-2, -1, 0)
  Param.add("SubWaveform", 0.0, 1.0, 0.0, 1.0)    -- Sub-Oscillator Waveform
  Param.add("SubVolume", 0.0, 1.0, 0.0)           -- Sub-Oscillator Level
  Param.add("Drive", 0.0, 1.0, 0.25)              -- Analog Overdrive Saturation
  Param.add("Slide", 0.0, 1.0, 0.0)               -- 60ms Portamento Legato Slide
end

function Eats303.process(time, freq, note, params, targetNote, isSlide, isAccent)
  local waveType = params["Waveform"] or 0.0
  local pitch = params["Pitch"] or 0.0
  local cutoff = params["Cutoff"] or 1400.0
  local res = params["Resonance"] or 9.2
  local envMod = params["EnvMod"] or 0.75
  local decay = params["Decay"] or 0.28
  local accent = params["Accent"] or 0.78
  local drive = params["Drive"] or params["Overdrive"] or 0.25
  local octave = math.floor((params["Octave"] or 0.0) + 0.5)
  local subWave = params["SubWaveform"] or 0.0
  local subVol = params["SubVolume"] or 0.0
  local slideParam = params["Slide"] or 0.0

  -- Pitch glide / Portamento logic for Eats-303 continuous monophonic voice
  local baseFreq = freq * (2.0 ^ (octave + pitch / 12.0))
  local currentFreq = baseFreq
  if targetNote and targetNote > 0 then
    local targetFreq = 440.0 * (2.0 ^ ((targetNote + octave * 12 + pitch - 69) / 12.0))
    currentFreq = targetFreq + (baseFreq - targetFreq) * math.exp(-time / 0.060)
  elseif isSlide or slideParam > 0.5 then
    local targetFreq = targetNote and (440.0 * (2.0 ^ ((targetNote + octave * 12 + pitch - 69) / 12.0))) or baseFreq
    currentFreq = targetFreq + (baseFreq - targetFreq) * math.exp(-time / 0.060)
  end

  -- Eats-303 Oscillators: Leaky Integrator Sawtooth & Differentiated Square
  local phase = time * currentFreq
  local normPhase = phase - math.floor(phase)
  local sawRaw = 2.0 * normPhase - 1.0
  local sawHP = sawRaw - 0.85 * math.exp(-time * 12.0)
  local sqrRaw = normPhase < 0.48 and 0.78 or -0.78
  local osc = (1.0 - waveType) * sawHP + waveType * sqrRaw

  if subVol > 0.01 then
    local subPhase = time * (currentFreq * 0.5)
    local subNorm = subPhase - math.floor(subPhase)
    local subOsc = subWave > 0.5 and (subNorm < 0.5 and 0.7 or -0.7) or math.sin(6.283185 * subNorm)
    osc = osc * (1.0 - subVol * 0.4) + subOsc * (subVol * 0.6)
  end

  -- Dynamic Accent & VCF Envelope Decay Dynamics (TB-303 / Open303 Model)
  local hasAccent = isAccent or (accent > 0.7 and not isSlide)
  local envBoost = hasAccent and (1.0 + accent * 1.25) or 1.0
  local activeDecay = hasAccent and 0.200 or (decay <= 1.0 and (0.200 + decay * 1.800) or decay)
  local softAttack = 1.0 - math.exp(-time / 0.003)
  local env = softAttack * math.exp(-time / activeDecay)
  local accentPulse = hasAccent and (accent * 0.55 * math.exp(-time / 0.035)) or 0.0

  -- 24dB 4-Pole Diode Ladder Filter with non-linear diode saturation
  local modCutoff = (cutoff * (2.0 ^ ((env + accentPulse) * envMod * 5.2 * envBoost)))
  local filtered = DSP.lowpass(osc, math.min(18000.0, math.max(30.0, modCutoff)), res)

  -- Post-VCF 150Hz 1-Pole High-Pass filter & overdrive saturation
  local highpassed = filtered * 0.985
  local output = highpassed * (hasAccent and (1.35 + accent * 0.45) or 1.0)
  if drive > 0.02 then
    output = math.tanh(output * (1.0 + drive * 3.5))
  end

  return output
end

function Eats303.gui()
  return {
    panel = {
      title = "EATS-303 ACID BASSLINE",
      subtitle = "Roland TB-303 Emulation • (JC-303 & Open303 DSP)",
      background = "silver",
      accent = "#000000",
      knobStyle = "chrome",
      layout = {
        {
          type = "row",
          children = {
            { type = "switch", param = "Waveform", label = "WAVEFORM", options = {"SAW", "SQR"} },
            { type = "divider", orientation = "vertical", height = 62 },
            { type = "knob", param = "Pitch", label = "PITCH", size = 52, knobStyle = "chrome" },
            { type = "knob", param = "Cutoff", label = "CUTOFF", size = 58, knobStyle = "chrome" },
            { type = "knob", param = "Resonance", label = "RESONANCE", size = 58, knobStyle = "chrome" },
            { type = "knob", param = "EnvMod", label = "ENV MOD", size = 54, knobStyle = "chrome" },
            { type = "knob", param = "Decay", label = "DECAY", size = 54, knobStyle = "chrome" },
            { type = "knob", param = "Accent", label = "ACCENT", size = 54, knobStyle = "chrome" },
          }
        },
        { type = "divider", orientation = "horizontal" },
        {
          type = "row",
          children = {
            { type = "knob", param = "Octave", label = "OCTAVE", size = 50, knobStyle = "chrome" },
            { type = "divider", orientation = "vertical", height = 56 },
            { type = "switch", param = "SubWaveform", label = "SUB OSC", options = {"SIN", "SQR"} },
            { type = "knob", param = "SubVolume", label = "SUB VOL", size = 52, knobStyle = "chrome" },
            { type = "divider", orientation = "vertical", height = 56 },
            { type = "slider", param = "Slide", label = "PORTAMENTO SLIDE", orientation = "horizontal", size = 140 },
            { type = "divider", orientation = "vertical", height = 56 },
            { type = "knob", param = "Drive", label = "DRIVE", size = 54, knobStyle = "chrome" },
          }
        }
      }
    }
  }
end

JC303 = Eats303

return Eats303

          ]],
          luaParams = {
            ["Waveform"] = 0.0000,
            ["Cutoff"] = 268.0808,
            ["Resonance"] = 15.2148,
            ["EnvMod"] = 0.0934,
            ["Decay"] = 0.0500,
            ["Accent"] = 0.2109,
            ["Slide"] = 0.8070,
            ["Overdrive"] = 0.0000,
          },
          steps = {
            [1] = { pitch = 36, velocity = 0.85, isSlide = false, isAccent = true },
            [3] = { pitch = 42, velocity = 0.85, isSlide = false, isAccent = true },
            [5] = { pitch = 36, velocity = 0.85, isSlide = false, isAccent = true },
            [7] = { pitch = 42, velocity = 0.85, isSlide = false, isAccent = true },
            [9] = { pitch = 36, velocity = 0.85, isSlide = false, isAccent = true },
            [11] = { pitch = 42, velocity = 0.85, isSlide = false, isAccent = true },
            [13] = { pitch = 36, velocity = 0.85, isSlide = false, isAccent = true },
            [15] = { pitch = 42, velocity = 0.85, isSlide = false, isAccent = true },
            [17] = { pitch = 36, velocity = 0.85, isSlide = false, isAccent = true },
            [19] = { pitch = 42, velocity = 0.85, isSlide = false, isAccent = true },
            [21] = { pitch = 36, velocity = 0.85, isSlide = false, isAccent = true },
            [23] = { pitch = 42, velocity = 0.85, isSlide = false, isAccent = true },
            [25] = { pitch = 36, velocity = 0.85, isSlide = false, isAccent = true },
            [27] = { pitch = 42, velocity = 0.85, isSlide = false, isAccent = true },
            [29] = { pitch = 36, velocity = 0.85, isSlide = false, isAccent = true },
            [31] = { pitch = 42, velocity = 0.85, isSlide = false, isAccent = true },
          },
          notes = {
            { id = "n1", pitch = 24, startStep = 0.00, durationSteps = 4.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "1785596545758", pitch = 36, startStep = 5.00, durationSteps = 1.00, velocity = 0.85, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "1785596549124", pitch = 36, startStep = 14.00, durationSteps = 1.00, velocity = 0.85, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "1785596552441", pitch = 36, startStep = 9.00, durationSteps = 1.00, velocity = 0.85, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "1785596555533", pitch = 27, startStep = 16.00, durationSteps = 4.00, velocity = 0.85, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "1785596626235", pitch = 39, startStep = 22.00, durationSteps = 1.00, velocity = 0.85, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "1785596627640", pitch = 39, startStep = 26.00, durationSteps = 1.00, velocity = 0.85, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "1785596802732", pitch = 42, startStep = 4.00, durationSteps = 1.03, velocity = 0.85, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "1785596816305", pitch = 42, startStep = 13.03, durationSteps = 1.00, velocity = 0.85, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "1785596880099", pitch = 48, startStep = 26.00, durationSteps = 4.00, velocity = 0.85, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "1785596894566", pitch = 24, startStep = 11.00, durationSteps = 1.00, velocity = 0.85, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "1785596917145", pitch = 27, startStep = 24.00, durationSteps = 1.00, velocity = 0.85, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "1785596922651", pitch = 27, startStep = 27.00, durationSteps = 1.00, velocity = 0.85, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "1785597140460", pitch = 27, startStep = 30.00, durationSteps = 2.00, velocity = 0.85, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
          },
          clips = {
            {
              id = "c_w1",
              name = "Acid 303 Riff",
              trackId = "t_lua_303",
              startBar = 0,
              barLength = 4,
              notes = {
                { id = "n1", pitch = 24, startStep = 0.00, durationSteps = 4.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "1785596545758", pitch = 36, startStep = 5.00, durationSteps = 1.00, velocity = 0.85, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "1785596549124", pitch = 36, startStep = 14.00, durationSteps = 1.00, velocity = 0.85, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "1785596552441", pitch = 36, startStep = 9.00, durationSteps = 1.00, velocity = 0.85, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "1785596555533", pitch = 27, startStep = 16.00, durationSteps = 4.00, velocity = 0.85, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "1785596626235", pitch = 39, startStep = 22.00, durationSteps = 1.00, velocity = 0.85, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "1785596627640", pitch = 39, startStep = 26.00, durationSteps = 1.00, velocity = 0.85, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "1785596802732", pitch = 42, startStep = 4.00, durationSteps = 1.03, velocity = 0.85, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "1785596816305", pitch = 42, startStep = 13.03, durationSteps = 1.00, velocity = 0.85, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "1785596880099", pitch = 48, startStep = 26.00, durationSteps = 4.00, velocity = 0.85, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "1785596894566", pitch = 24, startStep = 11.00, durationSteps = 1.00, velocity = 0.85, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "1785596917145", pitch = 27, startStep = 24.00, durationSteps = 1.00, velocity = 0.85, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "1785596922651", pitch = 27, startStep = 27.00, durationSteps = 1.00, velocity = 0.85, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "1785597140460", pitch = 27, startStep = 30.00, durationSteps = 2.00, velocity = 0.85, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
              },
            },
          },
          fxRack = {
            { id = "fx_td", name = "TubeDistortion", type = "distortion", enabled = true, mix = 0.50, params = { ["Drive"] = 6.0000, ["OutGain"] = 0.7000 } },
          },
        },
      }
    },
    {
      id = "p1",
      name = "Pattern B",
      lengthSteps = 32,
      tracks = {
        {
          id = "p1_k",
          name = "Eats Kick",
          color = 0xffff007a,
          type = "luaScript",
          volume = 0.950,
          pan = 0.000,
          isMuted = false,
          isSoloed = false,
          sampleName = "kick",
          synthWaveform = "sawtooth",
          cutoff = 3000.0,
          resonance = 1.00,
          attack = 0.010,
          release = 0.300,
          trackerColumns = 4,
          activeView = "pianoRoll",
          luaScriptCode = [[
-- --- Procedural Sub Kick Drum Script (Lua) ---
local ProceduralKick = {}

function ProceduralKick.init()
  Param.add("StartFreq", 100.0, 300.0, 160.0)
  Param.add("EndFreq", 30.0, 60.0, 42.0)
  Param.add("PitchDecay", 0.01, 0.2, 0.035)
  Param.add("AmpDecay", 0.05, 4.0, 0.35)
  Param.add("Click", 0.0, 1.0, 0.0)
end

function ProceduralKick.process(time, freq, note, params)
  local startF = params["StartFreq"] or 160.0
  local endF = params["EndFreq"] or 42.0
  local pDecay = params["PitchDecay"] or 0.035
  local aDecay = params["AmpDecay"] or 0.35
  local click = params["Click"] or 0.0

  -- Pitch sweep envelope
  local curFreq = endF + (startF - endF) * math.exp(-time / math.max(0.005, pDecay))
  local phase = 2.0 * math.pi * curFreq * time
  local subSine = math.sin(phase)

  -- Transient click
  local clickTransient = (math.random() * 2.0 - 1.0) * math.exp(-time * 150.0) * click

  -- Amplitude envelope decaying cleanly
  local env = math.exp(-time * 4.0 / math.max(0.01, aDecay))
  local rawOutput = (subSine * 0.85 + clickTransient * 0.15) * env

  -- Smooth fade toward edge of kick duration to guarantee clean drop to silence
  local maxDur = math.max(0.1, aDecay)
  local fadeStart = maxDur - 0.04
  local edgeFade = 1.0
  if time > fadeStart then
    local norm = math.max(0.0, math.min(1.0, (maxDur - time) / 0.04))
    edgeFade = 0.5 * (1.0 - math.cos(math.pi * norm))
  end
  if time >= maxDur then edgeFade = 0.0 end
  return math.tanh(rawOutput * edgeFade * 1.3)
end

return ProceduralKick

          ]],
          luaParams = {
            ["StartFreq"] = 160.0000,
            ["EndFreq"] = 42.0000,
            ["PitchDecay"] = 0.0350,
            ["AmpDecay"] = 0.3500,
            ["Click"] = 0.0000,
          },
          steps = {
            [1] = { pitch = 36, velocity = 0.95, isSlide = false, isAccent = true },
            [5] = { pitch = 36, velocity = 0.95, isSlide = false, isAccent = true },
            [9] = { pitch = 36, velocity = 0.95, isSlide = false, isAccent = true },
            [13] = { pitch = 36, velocity = 0.95, isSlide = false, isAccent = true },
            [17] = { pitch = 36, velocity = 0.95, isSlide = false, isAccent = true },
            [21] = { pitch = 36, velocity = 0.95, isSlide = false, isAccent = true },
            [25] = { pitch = 36, velocity = 0.95, isSlide = false, isAccent = true },
            [29] = { pitch = 36, velocity = 0.95, isSlide = false, isAccent = true },
          },
          notes = {
            { id = "k_0", pitch = 36, startStep = 0.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "k_4", pitch = 36, startStep = 4.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "k_8", pitch = 36, startStep = 8.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "k_12", pitch = 36, startStep = 12.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "k_16", pitch = 36, startStep = 16.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "k_20", pitch = 36, startStep = 20.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "k_24", pitch = 36, startStep = 24.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "k_28", pitch = 36, startStep = 28.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
          },
          clips = {
            {
              id = "c_k1",
              name = "Kick Beat A",
              trackId = "t_kick",
              startBar = 0,
              barLength = 4,
              notes = {
                { id = "k_0", pitch = 36, startStep = 0.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "k_4", pitch = 36, startStep = 4.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "k_8", pitch = 36, startStep = 8.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "k_12", pitch = 36, startStep = 12.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "k_16", pitch = 36, startStep = 16.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "k_20", pitch = 36, startStep = 20.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "k_24", pitch = 36, startStep = 24.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "k_28", pitch = 36, startStep = 28.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
              },
            },
          },
        },
        {
          id = "p1_s",
          name = "Eats Snare",
          color = 0xffff8c00,
          type = "luaScript",
          volume = 0.850,
          pan = 0.000,
          isMuted = false,
          isSoloed = false,
          sampleName = "kick",
          synthWaveform = "sawtooth",
          cutoff = 3000.0,
          resonance = 1.00,
          attack = 0.010,
          release = 0.300,
          trackerColumns = 4,
          activeView = "pianoRoll",
          luaScriptCode = [[
-- --- Procedural Snare Drum Script (Lua) ---
local ProceduralSnare = {}

function ProceduralSnare.init()
  Param.add("ToneFreq", 100.0, 320.0, 185.0)
  Param.add("Snappy", 0.0, 1.0, 0.65)
  Param.add("Decay", 0.05, 0.8, 0.18)
  Param.add("Variation", 0.0, 1.0, 0.0)
end

function ProceduralSnare.process(time, freq, note, params)
  local toneFreq = params["ToneFreq"] or 185.0
  local snappy = params["Snappy"] or 0.65
  local decay = params["Decay"] or 0.18
  local variation = params["Variation"] or 0.0

  if variation > 0.001 then
    local vOffset = (math.sin(note * 12.9898) * 0.5 + 0.5) * variation
    toneFreq = toneFreq * (1.0 + (vOffset - 0.5 * variation) * 0.08)
    decay = decay * (1.0 + (vOffset - 0.5 * variation) * 0.15)
  end

  local sweepFreq = toneFreq * (1.0 + 1.2 * math.exp(-time * 60.0))
  local body = math.sin(2.0 * math.pi * sweepFreq * time) * math.exp(-time * 22.0)
  local overtone = math.sin(2.0 * math.pi * (toneFreq * 1.75) * time) * math.exp(-time * 30.0) * 0.35
  local tonalCore = body + overtone

  local noise = (math.random() * 2.0 - 1.0) * math.exp(-time / math.max(0.01, decay))
  local filteredNoise = DSP.highpass(noise, 1800.0, 1.2)

  local click = (math.random() * 2.0 - 1.0) * math.exp(-time * 250.0) * 0.25

  local output = (tonalCore * (1.0 - snappy * 0.6) + filteredNoise * (snappy * 1.2) + click)
  return math.tanh(output * 1.3)
end

return ProceduralSnare

          ]],
          luaParams = {
            ["ToneFreq"] = 185.0000,
            ["Snappy"] = 0.6500,
            ["Decay"] = 0.1000,
          },
          steps = {
            [5] = { pitch = 38, velocity = 0.90, isSlide = false, isAccent = true },
            [13] = { pitch = 38, velocity = 0.90, isSlide = false, isAccent = true },
            [21] = { pitch = 38, velocity = 0.90, isSlide = false, isAccent = true },
            [29] = { pitch = 38, velocity = 0.90, isSlide = false, isAccent = true },
          },
          notes = {
            { id = "s_4", pitch = 38, startStep = 4.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "s_12", pitch = 38, startStep = 12.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "s_20", pitch = 38, startStep = 20.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "s_28", pitch = 38, startStep = 28.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
          },
          clips = {
            {
              id = "c_s1",
              name = "Snare Pattern",
              trackId = "t_snare",
              startBar = 0,
              barLength = 4,
              notes = {
                { id = "s_4", pitch = 38, startStep = 4.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "s_12", pitch = 38, startStep = 12.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "s_20", pitch = 38, startStep = 20.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "s_28", pitch = 38, startStep = 28.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
              },
            },
          },
        },
        {
          id = "p1_h",
          name = "Eats Hats",
          color = 0xffffb700,
          type = "luaScript",
          volume = 0.750,
          pan = 0.000,
          isMuted = false,
          isSoloed = false,
          sampleName = "kick",
          synthWaveform = "sawtooth",
          cutoff = 3000.0,
          resonance = 1.00,
          attack = 0.010,
          release = 0.300,
          trackerColumns = 4,
          activeView = "pianoRoll",
          luaScriptCode = [[
-- --- Procedural Hi-Hat Synth Script (Lua) ---
local ProceduralHiHat = {}

function ProceduralHiHat.init()
  Param.add("Cutoff", 3000.0, 14000.0, 7500.0)
  Param.add("Decay", 0.01, 0.6, 0.06)
  Param.add("Metallic", 0.0, 1.0, 0.15)
  Param.add("Variation", 0.0, 1.0, 0.0)
end

function ProceduralHiHat.process(time, freq, note, params)
  local cutoff = params["Cutoff"] or 7500.0
  local decay = params["Decay"] or 0.06
  local metallic = params["Metallic"] or 0.15
  local variation = params["Variation"] or 0.0

  if variation > 0.001 then
    local vOffset = (math.sin(note * 78.233) * 0.5 + 0.5) * variation
    cutoff = cutoff * (1.0 + (vOffset - 0.5 * variation) * 0.12)
    decay = decay * (1.0 + (vOffset - 0.5 * variation) * 0.18)
  end

  local env = math.exp(-time / math.max(0.005, decay))

  local ring1 = math.sin(2.0 * math.pi * 320.0 * time)
  local ring2 = math.sin(2.0 * math.pi * 540.0 * time)
  local ring3 = math.sin(2.0 * math.pi * 890.0 * time)
  local metallicRing = (ring1 + ring2 + ring3) * 0.333

  local noise = (math.random() * 2.0 - 1.0)
  local rawSignal = noise * (1.0 - metallic * 0.3) + metallicRing * (metallic * 0.3)
  local filtered = DSP.highpass(rawSignal, cutoff, 1.4)

  return math.tanh(filtered * env * 1.1)
end

return ProceduralHiHat

          ]],
          luaParams = {
            ["Cutoff"] = 8500.0000,
            ["Decay"] = 0.0500,
            ["Metallic"] = 0.1500,
          },
          steps = {
            [1] = { pitch = 42, velocity = 0.60, isSlide = false, isAccent = false },
            [3] = { pitch = 42, velocity = 0.90, isSlide = false, isAccent = true },
            [5] = { pitch = 42, velocity = 0.60, isSlide = false, isAccent = false },
            [7] = { pitch = 42, velocity = 0.90, isSlide = false, isAccent = true },
            [9] = { pitch = 42, velocity = 0.60, isSlide = false, isAccent = false },
            [11] = { pitch = 42, velocity = 0.90, isSlide = false, isAccent = true },
            [13] = { pitch = 42, velocity = 0.60, isSlide = false, isAccent = false },
            [15] = { pitch = 42, velocity = 0.90, isSlide = false, isAccent = true },
            [17] = { pitch = 42, velocity = 0.60, isSlide = false, isAccent = false },
            [19] = { pitch = 42, velocity = 0.90, isSlide = false, isAccent = true },
            [21] = { pitch = 42, velocity = 0.60, isSlide = false, isAccent = false },
            [23] = { pitch = 42, velocity = 0.90, isSlide = false, isAccent = true },
            [25] = { pitch = 42, velocity = 0.60, isSlide = false, isAccent = false },
            [27] = { pitch = 42, velocity = 0.90, isSlide = false, isAccent = true },
            [29] = { pitch = 42, velocity = 0.60, isSlide = false, isAccent = false },
            [31] = { pitch = 42, velocity = 0.90, isSlide = false, isAccent = true },
          },
          notes = {
            { id = "h_0", pitch = 42, startStep = 0.00, durationSteps = 1.00, velocity = 0.60, column = 0, effectCommand = "00", isSlide = false, isAccent = false },
            { id = "h_2", pitch = 42, startStep = 2.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "h_4", pitch = 42, startStep = 4.00, durationSteps = 1.00, velocity = 0.60, column = 0, effectCommand = "00", isSlide = false, isAccent = false },
            { id = "h_6", pitch = 42, startStep = 6.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "h_8", pitch = 42, startStep = 8.00, durationSteps = 1.00, velocity = 0.60, column = 0, effectCommand = "00", isSlide = false, isAccent = false },
            { id = "h_10", pitch = 42, startStep = 10.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "h_12", pitch = 42, startStep = 12.00, durationSteps = 1.00, velocity = 0.60, column = 0, effectCommand = "00", isSlide = false, isAccent = false },
            { id = "h_14", pitch = 42, startStep = 14.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "h_16", pitch = 42, startStep = 16.00, durationSteps = 1.00, velocity = 0.60, column = 0, effectCommand = "00", isSlide = false, isAccent = false },
            { id = "h_18", pitch = 42, startStep = 18.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "h_20", pitch = 42, startStep = 20.00, durationSteps = 1.00, velocity = 0.60, column = 0, effectCommand = "00", isSlide = false, isAccent = false },
            { id = "h_22", pitch = 42, startStep = 22.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = t
              startBar = 0,
              barLength = 4,
              notes = {
                { id = "h_0", pitch = 42, startStep = 0.00, durationSteps = 1.00, velocity = 0.60, column = 0, effectCommand = "00", isSlide = false, isAccent = false },
                { id = "h_2", pitch = 42, startStep = 2.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "h_4", pitch = 42, startStep = 4.00, durationSteps = 1.00, velocity = 0.60, column = 0, effectCommand = "00", isSlide = false, isAccent = false },
                { id = "h_6", pitch = 42, startStep = 6.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "h_8", pitch = 42, startStep = 8.00, durationSteps = 1.00, velocity = 0.60, column = 0, effectCommand = "00", isSlide = false, isAccent = false },
                { id = "h_10", pitch = 42, startStep = 10.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "h_12", pitch = 42, startStep = 12.00, durationSteps = 1.00, velocity = 0.60, column = 0, effectCommand = "00", isSlide = false, isAccent = false },
                { id = "h_14", pitch = 42, startStep = 14.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "h_16", pitch = 42, startStep = 16.00, durationSteps = 1.00, velocity = 0.60, column = 0, effectCommand = "00", isSlide = false, isAccent = false },
                { id = "h_18", pitch = 42, startStep = 18.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "h_20", pitch = 42, startStep = 20.00, durationSteps = 1.00, velocity = 0.60, column = 0, effectCommand = "00", isSlide = false, isAccent = false },
                { id = "h_22", pitch = 42, startStep = 22.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "h_24", pitch = 42, startStep = 24.00, durationSteps = 1.00, velocity = 0.60, column = 0, effectCommand = "00", isSlide = false, isAccent = false },
                { id = "h_26", pitch = 42, startStep = 26.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "h_28", pitch = 42, startStep = 28.00, durationSteps = 1.00, velocity = 0.60, column = 0, effectCommand = "00", isSlide = false, isAccent = false },
                { id = "h_30", pitch = 42, startStep = 30.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
              },
            },
          },
        },
        {
          id = "p1_w",
          name = "Eats-303",
          color = 0xff00ff66,
          type = "luaScript",
          volume = 0.900,
          pan = 0.000,
          isMuted = false,
          isSoloed = false,
          sampleName = "kick",
          synthWaveform = "sawtooth",
          cutoff = 3000.0,
          resonance = 1.00,
          attack = 0.010,
          release = 0.300,
          trackerColumns = 4,
          activeView = "pianoRoll",
          luaScriptCode = [[
-- --- Eats-303 Acid Bassline (JC-303 & Open303 DSP) ---
local Eats303 = {}

function Eats303.init()
  Param.add("Waveform", 0.0, 1.0, 0.0, 1.0)       -- 0 = Saw, 1 = Square
  Param.add("Pitch", -12.0, 12.0, 0.0, 1.0)       -- Tuning semitones
  Param.add("Cutoff", 200.0, 4500.0, 1400.0)      -- Base VCF Cutoff
  Param.add("Resonance", 0.5, 16.0, 9.2)          -- Diode Ladder Q with 150Hz Feedback HPF
  Param.add("EnvMod", 0.0, 1.0, 0.75)             -- Exponential VCF Envelope Sweep
  Param.add("Decay", 0.05, 1.2, 0.28)             -- Non-accented Decay (forced 200ms on Accent)
  Param.add("Accent", 0.0, 1.0, 0.78)             -- Accent Cutoff Pulse & Gain Boost
  Param.add("Octave", -2.0, 0.0, 0.0, 1.0)        -- Octave Transpose (-2, -1, 0)
  Param.add("SubWaveform", 0.0, 1.0, 0.0, 1.0)    -- Sub-Oscillator Waveform
  Param.add("SubVolume", 0.0, 1.0, 0.0)           -- Sub-Oscillator Level
  Param.add("Drive", 0.0, 1.0, 0.25)              -- Analog Overdrive Saturation
  Param.add("Slide", 0.0, 1.0, 0.0)               -- 60ms Portamento Legato Slide
end

function Eats303.process(time, freq, note, params, targetNote, isSlide, isAccent)
  local waveType = params["Waveform"] or 0.0
  local pitch = params["Pitch"] or 0.0
  local cutoff = params["Cutoff"] or 1400.0
  local res = params["Resonance"] or 9.2
  local envMod = params["EnvMod"] or 0.75
  local decay = params["Decay"] or 0.28
  local accent = params["Accent"] or 0.78
  local drive = params["Drive"] or params["Overdrive"] or 0.25
  local octave = math.floor((params["Octave"] or 0.0) + 0.5)
  local subWave = params["SubWaveform"] or 0.0
  local subVol = params["SubVolume"] or 0.0
  local slideParam = params["Slide"] or 0.0

  -- Pitch glide / Portamento logic for Eats-303 continuous monophonic voice
  local baseFreq = freq * (2.0 ^ (octave + pitch / 12.0))
  local currentFreq = baseFreq
  if targetNote and targetNote > 0 then
    local targetFreq = 440.0 * (2.0 ^ ((targetNote + octave * 12 + pitch - 69) / 12.0))
    currentFreq = targetFreq + (baseFreq - targetFreq) * math.exp(-time / 0.060)
  elseif isSlide or slideParam > 0.5 then
    local targetFreq = targetNote and (440.0 * (2.0 ^ ((targetNote + octave * 12 + pitch - 69) / 12.0))) or baseFreq
    currentFreq = targetFreq + (baseFreq - targetFreq) * math.exp(-time / 0.060)
  end

  -- Eats-303 Oscillators: Leaky Integrator Sawtooth & Differentiated Square
  local phase = time * currentFreq
  local normPhase = phase - math.floor(phase)
  local sawRaw = 2.0 * normPhase - 1.0
  local sawHP = sawRaw - 0.85 * math.exp(-time * 12.0)
  local sqrRaw = normPhase < 0.48 and 0.78 or -0.78
  local osc = (1.0 - waveType) * sawHP + waveType * sqrRaw

  if subVol > 0.01 then
    local subPhase = time * (currentFreq * 0.5)
    local subNorm = subPhase - math.floor(subPhase)
    local subOsc = subWave > 0.5 and (subNorm < 0.5 and 0.7 or -0.7) or math.sin(6.283185 * subNorm)
    osc = osc * (1.0 - subVol * 0.4) + subOsc * (subVol * 0.6)
  end

  -- Dynamic Accent & VCF Envelope Decay Dynamics (TB-303 / Open303 Model)
  local hasAccent = isAccent or (accent > 0.7 and not isSlide)
  local envBoost = hasAccent and (1.0 + accent * 1.25) or 1.0
  local activeDecay = hasAccent and 0.200 or (decay <= 1.0 and (0.200 + decay * 1.800) or decay)
  local softAttack = 1.0 - math.exp(-time / 0.003)
  local env = softAttack * math.exp(-time / activeDecay)
  local accentPulse = hasAccent and (accent * 0.55 * math.exp(-time / 0.035)) or 0.0

  -- 24dB 4-Pole Diode Ladder Filter with non-linear diode saturation
  local modCutoff = (cutoff * (2.0 ^ ((env + accentPulse) * envMod * 5.2 * envBoost)))
  local filtered = DSP.lowpass(osc, math.min(18000.0, math.max(30.0, modCutoff)), res)

  -- Post-VCF 150Hz 1-Pole High-Pass filter & overdrive saturation
  local highpassed = filtered * 0.985
  local output = highpassed * (hasAccent and (1.35 + accent * 0.45) or 1.0)
  if drive > 0.02 then
    output = math.tanh(output * (1.0 + drive * 3.5))
  end

  return output
end

function Eats303.gui()
  return {
    panel = {
      title = "EATS-303 ACID BASSLINE",
      subtitle = "Roland TB-303 Emulation • (JC-303 & Open303 DSP)",
      background = "silver",
      accent = "#000000",
      knobStyle = "chrome",
      layout = {
        {
          type = "row",
          children = {
            { type = "switch", param = "Waveform", label = "WAVEFORM", options = {"SAW", "SQR"} },
            { type = "divider", orientation = "vertical", height = 62 },
            { type = "knob", param = "Pitch", label = "PITCH", size = 52, knobStyle = "chrome" },
            { type = "knob", param = "Cutoff", label = "CUTOFF", size = 58, knobStyle = "chrome" },
            { type = "knob", param = "Resonance", label = "RESONANCE", size = 58, knobStyle = "chrome" },
            { type = "knob", param = "EnvMod", label = "ENV MOD", size = 54, knobStyle = "chrome" },
            { type = "knob", param = "Decay", label = "DECAY", size = 54, knobStyle = "chrome" },
            { type = "knob", param = "Accent", label = "ACCENT", size = 54, knobStyle = "chrome" },
          }
        },
        { type = "divider", orientation = "horizontal" },
        {
          type = "row",
          children = {
            { type = "knob", param = "Octave", label = "OCTAVE", size = 50, knobStyle = "chrome" },
            { type = "divider", orientation = "vertical", height = 56 },
            { type = "switch", param = "SubWaveform", label = "SUB OSC", options = {"SIN", "SQR"} },
            { type = "knob", param = "SubVolume", label = "SUB VOL", size = 52, knobStyle = "chrome" },
            { type = "divider", orientation = "vertical", height = 56 },
            { type = "slider", param = "Slide", label = "PORTAMENTO SLIDE", orientation = "horizontal", size = 140 },
            { type = "divider", orientation = "vertical", height = 56 },
            { type = "knob", param = "Drive", label = "DRIVE", size = 54, knobStyle = "chrome" },
          }
        }
      }
    }
  }
end

JC303 = Eats303

return Eats303
          ]],
          luaParams = {
            ["Waveform"] = 0.0000,
            ["Cutoff"] = 1800.0000,
            ["Resonance"] = 8.0000,
            ["EnvMod"] = 0.7500,
            ["Decay"] = 0.2800,
            ["Accent"] = 0.6000,
            ["Slide"] = 0.4000,
            ["Overdrive"] = 0.3000,
          },
          steps = {
            [1] = { pitch = 36, velocity = 0.85, isSlide = false, isAccent = true },
            [3] = { pitch = 42, velocity = 0.85, isSlide = false, isAccent = true },
            [5] = { pitch = 36, velocity = 0.85, isSlide = false, isAccent = true },
            [7] = { pitch = 42, velocity = 0.85, isSlide = false, isAccent = true },
            [9] = { pitch = 36, velocity = 0.85, isSlide = false, isAccent = true },
            [11] = { pitch = 42, velocity = 0.85, isSlide = false, isAccent = true },
            [13] = { pitch = 36, velocity = 0.85, isSlide = false, isAccent = true },
            [15] = { pitch = 42, velocity = 0.85, isSlide = false, isAccent = true },
            [17] = { pitch = 36, velocity = 0.85, isSlide = false, isAccent = true },
            [19] = { pitch = 42, velocity = 0.85, isSlide = false, isAccent = true },
            [21] = { pitch = 36, velocity = 0.85, isSlide = false, isAccent = true },
            [23] = { pitch = 42, velocity = 0.85, isSlide = false, isAccent = true },
            [25] = { pitch = 36, velocity = 0.85, isSlide = false, isAccent = true },
            [27] = { pitch = 42, velocity = 0.85, isSlide = false, isAccent = true },
            [29] = { pitch = 36, velocity = 0.85, isSlide = false, isAccent = true },
            [31] = { pitch = 42, velocity = 0.85, isSlide = false, isAccent = true },
          },
          notes = {
            { id = "n1", pitch = 36, startStep = 0.00, durationSteps = 2.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "n2", pitch = 36, startStep = 2.00, durationSteps = 1.00, velocity = 0.80, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "n3", pitch = 48, startStep = 3.00, durationSteps = 1.00, velocity = 1.00, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "n4", pitch = 39, startStep = 4.00, durationSteps = 2.00, velocity = 0.85, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "n5", pitch = 41, startStep = 6.00, durationSteps = 2.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "n6", pitch = 43, startStep = 8.00, durationSteps = 2.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "n7", pitch = 36, startStep = 10.00, durationSteps = 2.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "n8", pitch = 48, startStep = 12.00, durationSteps = 2.00, velocity = 1.00, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "n9", pitch = 46, startStep = 14.00, durationSteps = 2.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
          },
          clips = {
            {
              id = "c_w1",
              name = "Acid 303 Riff",
              trackId = "t_lua_303",
              startBar = 0,
              barLength = 4,
              notes = {
                { id = "n1", pitch = 36, startStep = 0.00, durationSteps = 2.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "n2", pitch = 36, startStep = 2.00, durationSteps = 1.00, velocity = 0.80, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "n3", pitch = 48, startStep = 3.00, durationSteps = 1.00, velocity = 1.00, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "n4", pitch = 39, startStep = 4.00, durationSteps = 2.00, velocity = 0.85, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "n5", pitch = 41, startStep = 6.00, durationSteps = 2.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "n6", pitch = 43, startStep = 8.00, durationSteps = 2.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "n7", pitch = 36, startStep = 10.00, durationSteps = 2.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "n8", pitch = 48, startStep = 12.00, durationSteps = 2.00, velocity = 1.00, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "n9", pitch = 46, startStep = 14.00, durationSteps = 2.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
              },
            },
          },
        },
      }
    },
  },

  arranger = {
    activePatternIndex = 0,
    items = {
      { patternId = "p0", startBar = 0, barLength = 4 },
      { patternId = "p1", startBar = 4, barLength = 4 },
    }
  }
}
''';
}
