import '../models/daw_state.dart';
import '../models/track_model.dart';

class EatsLuaSerializer {
  /// Serializes a full [DawState] object into a formatted `.eats.lua` script.
  static String serialize(DawState dawState, {String projectName = 'Untitled Song'}) {
    final buffer = StringBuffer();

    buffer.writeln('-- Eatsbits Song File: "${_escapeString(projectName)}"');
    buffer.writeln('-- Generated by Eatsbits DAW');
    buffer.writeln();
    buffer.writeln('return eatsbits.song {');
    buffer.writeln('  version = "1.0",');

    // 1. Meta / Transport settings
    buffer.writeln('  meta = {');
    buffer.writeln('    title = "${_escapeString(dawState.projectName)}",');
    buffer.writeln('    author = "${_escapeString(dawState.authorName)}",');
    buffer.writeln('    bpm = ${dawState.bpm.toStringAsFixed(2)},');
    buffer.writeln('    masterVolume = ${dawState.masterVolume.toStringAsFixed(2)},');
    buffer.writeln('    isSongMode = ${dawState.isSongMode},');
    buffer.writeln('    isLooping = ${dawState.isLooping},');
    buffer.writeln('    loopStartBar = ${dawState.loopStartBar},');
    buffer.writeln('    loopEndBar = ${dawState.loopEndBar},');
    buffer.writeln('  },');
    buffer.writeln();

    // 2. Patterns & Track Channels
    buffer.writeln('  patterns = {');
    for (final pattern in dawState.patterns) {
      buffer.writeln('    {');
      buffer.writeln('      id = "${_escapeString(pattern.id)}",');
      buffer.writeln('      name = "${_escapeString(pattern.name)}",');
      buffer.writeln('      lengthSteps = ${pattern.lengthSteps},');
      buffer.writeln('      tracks = {');
      for (final track in pattern.tracks) {
        _serializeTrack(buffer, track, indent: '        ');
      }
      buffer.writeln('      }');
      buffer.writeln('    },');
    }
    buffer.writeln('  },');
    buffer.writeln();

    // 3. Arranger timeline
    buffer.writeln('  arranger = {');
    buffer.writeln('    activePatternIndex = ${dawState.activePatternIndex},');
    buffer.writeln('    items = {');
    for (final item in dawState.arrangement) {
      buffer.writeln('      { patternId = "${_escapeString(item.patternId)}", startBar = ${item.startBar}, barLength = ${item.barLength} },');
    }
    buffer.writeln('    }');
    buffer.writeln('  }');
    buffer.writeln('}');

    return buffer.toString();
  }

  static void _serializeTrack(StringBuffer buffer, TrackChannel track, {required String indent}) {
    buffer.writeln('$indent{');
    final childIndent = '$indent  ';

    buffer.writeln('${childIndent}id = "${_escapeString(track.id)}",');
    buffer.writeln('${childIndent}name = "${_escapeString(track.name)}",');
    buffer.writeln('${childIndent}color = 0x${track.color.value.toRadixString(16).padLeft(8, '0')},');
    buffer.writeln('${childIndent}type = "${track.type.name}",');
    buffer.writeln('${childIndent}volume = ${track.volume.toStringAsFixed(3)},');
    buffer.writeln('${childIndent}pan = ${track.pan.toStringAsFixed(3)},');
    buffer.writeln('${childIndent}isMuted = ${track.isMuted},');
    buffer.writeln('${childIndent}isSoloed = ${track.isSoloed},');

    // Instrument parameters
    buffer.writeln('${childIndent}sampleName = "${_escapeString(track.sampleName)}",');
    buffer.writeln('${childIndent}synthWaveform = "${_escapeString(track.synthWaveform)}",');
    buffer.writeln('${childIndent}cutoff = ${track.cutoff.toStringAsFixed(1)},');
    buffer.writeln('${childIndent}resonance = ${track.resonance.toStringAsFixed(2)},');
    buffer.writeln('${childIndent}attack = ${track.attack.toStringAsFixed(3)},');
    buffer.writeln('${childIndent}release = ${track.release.toStringAsFixed(3)},');
    buffer.writeln('${childIndent}trackerColumns = ${track.trackerColumns},');
    buffer.writeln('${childIndent}activeView = "${track.activeView.name}",');

    // Lua plugin script & params
    if (track.luaScriptCode.isNotEmpty) {
      buffer.writeln('${childIndent}luaScriptCode = ${_formatLuaString(track.luaScriptCode, childIndent)},');
    }
    if (track.luaParams.isNotEmpty) {
      buffer.writeln('${childIndent}luaParams = {');
      track.luaParams.forEach((key, val) {
        buffer.writeln('$childIndent  ["${_escapeString(key)}"] = ${val.toStringAsFixed(4)},');
      });
      buffer.writeln('${childIndent}},');
    }

    // Step sequencer events
    final activeSteps = <int, StepEvent>{};
    for (int i = 0; i < track.steps.length; i++) {
      if (track.steps[i].active) {
        activeSteps[i] = track.steps[i];
      }
    }
    if (activeSteps.isNotEmpty) {
      buffer.writeln('${childIndent}steps = {');
      activeSteps.forEach((stepIdx, step) {
        buffer.writeln('$childIndent  [${stepIdx + 1}] = { pitch = ${step.pitch}, velocity = ${step.velocity.toStringAsFixed(2)}, isSlide = ${step.isSlide}, isAccent = ${step.isAccent} },');
      });
      buffer.writeln('${childIndent}},');
    }

    // Piano Roll Notes
    if (track.notes.isNotEmpty) {
      buffer.writeln('${childIndent}notes = {');
      for (final n in track.notes) {
        buffer.writeln('$childIndent  { id = "${_escapeString(n.id)}", pitch = ${n.pitch}, startStep = ${n.startStep.toStringAsFixed(2)}, durationSteps = ${n.durationSteps.toStringAsFixed(2)}, velocity = ${n.velocity.toStringAsFixed(2)}, column = ${n.column}, effectCommand = "${_escapeString(n.effectCommand)}", isSlide = ${n.isSlide}, isAccent = ${n.isAccent} },');
      }
      buffer.writeln('${childIndent}},');
    }

    // Clips
    if (track.clips.isNotEmpty) {
      buffer.writeln('${childIndent}clips = {');
      for (final clip in track.clips) {
        _serializeClip(buffer, clip, indent: '$childIndent  ');
      }
      buffer.writeln('${childIndent}},');
    }

    // FX Racks
    if (track.fxRack.isNotEmpty) {
      buffer.writeln('${childIndent}fxRack = {');
      for (final fx in track.fxRack) {
        buffer.writeln('$childIndent  { id = "${_escapeString(fx.id)}", name = "${_escapeString(fx.name)}", type = "${fx.type.name}", enabled = ${fx.enabled}, mix = ${fx.mix.toStringAsFixed(2)}, params = ${_formatMap(fx.params)} },');
      }
      buffer.writeln('${childIndent}},');
    }

    // MIDI FX Racks
    if (track.midiFXRack.isNotEmpty) {
      buffer.writeln('${childIndent}midiFXRack = {');
      for (final mfx in track.midiFXRack) {
        buffer.writeln('$childIndent  { id = "${_escapeString(mfx.id)}", name = "${_escapeString(mfx.name)}", enabled = ${mfx.enabled}, luaScriptCode = ${_formatLuaString(mfx.luaScriptCode, childIndent)}, luaParams = ${_formatMap(mfx.luaParams)} },');
      }
      buffer.writeln('${childIndent}},');
    }

    buffer.writeln('$indent},');
  }

  static void _serializeClip(StringBuffer buffer, TrackClip clip, {required String indent}) {
    buffer.writeln('$indent{');
    final childIndent = '$indent  ';
    buffer.writeln('${childIndent}id = "${_escapeString(clip.id)}",');
    buffer.writeln('${childIndent}name = "${_escapeString(clip.name)}",');
    buffer.writeln('${childIndent}trackId = "${_escapeString(clip.trackId)}",');
    buffer.writeln('${childIndent}startBar = ${clip.startBar},');
    buffer.writeln('${childIndent}barLength = ${clip.barLength},');

    if (clip.luaScriptCode.isNotEmpty) {
      buffer.writeln('${childIndent}luaScriptCode = ${_formatLuaString(clip.luaScriptCode, childIndent)},');
    }
    if (clip.luaParams.isNotEmpty) {
      buffer.writeln('${childIndent}luaParams = ${_formatMap(clip.luaParams)},');
    }

    if (clip.notes.isNotEmpty) {
      buffer.writeln('${childIndent}notes = {');
      for (final n in clip.notes) {
        buffer.writeln('$childIndent  { id = "${_escapeString(n.id)}", pitch = ${n.pitch}, startStep = ${n.startStep.toStringAsFixed(2)}, durationSteps = ${n.durationSteps.toStringAsFixed(2)}, velocity = ${n.velocity.toStringAsFixed(2)}, column = ${n.column}, effectCommand = "${_escapeString(n.effectCommand)}", isSlide = ${n.isSlide}, isAccent = ${n.isAccent} },');
      }
      buffer.writeln('${childIndent}},');
    }
    buffer.writeln('$indent},');
  }

  static String _escapeString(String str) {
    return str
        .replaceAll('\\', '\\\\')
        .replaceAll('"', '\\"')
        .replaceAll('\n', '\\n')
        .replaceAll('\r', '\\r');
  }

  static String _formatLuaString(String str, String indent) {
    if (!str.contains('\n') && !str.contains('"')) {
      return '"${_escapeString(str)}"';
    }
    if (!str.contains(']]')) {
      return '[[\n$str\n$indent]]';
    }
    return '[=[\n$str\n$indent]=]';
  }

  static String _formatMap(Map<String, double> map) {
    if (map.isEmpty) return '{}';
    final parts = map.entries.map((e) => '["${_escapeString(e.key)}"] = ${e.value.toStringAsFixed(4)}').join(', ');
    return '{ $parts }';
  }
}
