import '../models/daw_state.dart';
import '../models/track_model.dart';
import '../models/automation_model.dart';
import '../models/lyric_model.dart';

class EatsLuaSerializer {
  /// Serializes a full [DawState] object into a formatted `.eats.lua` script.
  static String serialize(DawState dawState, {String projectName = 'Untitled Song'}) {
    final buffer = StringBuffer();

    buffer.writeln('-- Eatsbeats Song File: "${_escapeString(projectName)}"');
    buffer.writeln('-- Generated by Eatsbeats DAW');
    buffer.writeln();
    buffer.writeln('return eatsbeats.song {');
    buffer.writeln('  version = "1.0",');

    // 1. Meta / Transport settings
    buffer.writeln('  meta = {');
    buffer.writeln('    title = "${_escapeString(dawState.projectName)}",');
    buffer.writeln('    author = "${_escapeString(dawState.authorName)}",');
    buffer.writeln('    songKey = "${_escapeString(dawState.songKey)}",');
    buffer.writeln('    bpm = ${dawState.bpm.toStringAsFixed(2)},');
    buffer.writeln('    masterVolume = ${dawState.masterVolume.toStringAsFixed(2)},');
    buffer.writeln('    isSongMode = ${dawState.isSongMode},');
    buffer.writeln('    isLooping = ${dawState.isLooping},');
    buffer.writeln('    loopStartBar = ${dawState.loopStartBar},');
    buffer.writeln('    loopEndBar = ${dawState.loopEndBar},');
    if (dawState.masterLowGain != 0.0 || dawState.masterMidGain != 0.0 || dawState.masterHighGain != 0.0 || dawState.masterSubCut != 25.0) {
      buffer.writeln('    masterEq = {');
      buffer.writeln('      subCut = ${dawState.masterSubCut.toStringAsFixed(1)},');
      buffer.writeln('      lowGain = ${dawState.masterLowGain.toStringAsFixed(2)},');
      buffer.writeln('      midFreq = ${dawState.masterMidFreq.toStringAsFixed(1)},');
      buffer.writeln('      midGain = ${dawState.masterMidGain.toStringAsFixed(2)},');
      buffer.writeln('      highGain = ${dawState.masterHighGain.toStringAsFixed(2)},');
      buffer.writeln('    },');
    }
    buffer.writeln('    masterLimiter = {');
    buffer.writeln('      enabled = ${dawState.masterLimiterEnabled},');
    buffer.writeln('      ceilingDbfs = ${dawState.masterCeilingDbfs.toStringAsFixed(2)},');
    buffer.writeln('      driveDb = ${dawState.masterLimiterDrive.toStringAsFixed(2)},');
    buffer.writeln('      targetLufs = ${dawState.masterTargetLufs.toStringAsFixed(1)},');
    buffer.writeln('    },');
    buffer.writeln('  },');
    buffer.writeln();

    // 2. Patterns & Track Channels
    buffer.writeln('  patterns = {');
    for (final pattern in dawState.patterns) {
      buffer.writeln('    {');
      buffer.writeln('      id = "${_escapeString(pattern.id)}",');
      buffer.writeln('      name = "${_escapeString(pattern.name)}",');
      buffer.writeln('      lengthSteps = ${pattern.lengthSteps},');
      buffer.writeln('      tracks = {');
      for (final track in pattern.tracks) {
        _serializeTrack(buffer, track, indent: '        ');
      }
      buffer.writeln('      }');
      buffer.writeln('    },');
    }
    buffer.writeln('  },');
    buffer.writeln();

    // 3. Arranger timeline
    buffer.writeln('  arranger = {');
    buffer.writeln('    activePatternIndex = ${dawState.activePatternIndex},');
    buffer.writeln('    items = {');
    for (final item in dawState.arrangement) {
      buffer.writeln('      { patternId = "${_escapeString(item.patternId)}", startBar = ${item.startBar}, barLength = ${item.barLength} },');
    }
    buffer.writeln('    }');
    buffer.writeln('  },');
    buffer.writeln();

    // 4. Chord Track
    if (dawState.chordTrack.isNotEmpty) {
      buffer.writeln('  chordTrack = {');
      for (final chord in dawState.chordTrack) {
        final bassStr = chord.bassPitchClass != null ? ', bassPitchClass = ${chord.bassPitchClass}' : '';
        buffer.writeln('    { id = "${_escapeString(chord.id)}", startBar = ${chord.startBar}, barLength = ${chord.barLength}, rootPitchClass = ${chord.rootPitchClass}, quality = "${chord.quality.name}"$bassStr },');
      }
      buffer.writeln('  },');
      buffer.writeln();
    } else {
      buffer.writeln('  chordTrack = {},');
      buffer.writeln();
    }

    // 5. Master FX Rack
    if (dawState.masterTrack.fxRack.isNotEmpty) {
      buffer.writeln('  masterFx = {');
      for (final fx in dawState.masterTrack.fxRack) {
        final irStr = fx.irSampleName != null ? ', irSampleName = "${_escapeString(fx.irSampleName!)}"' : '';
        final presetStr = fx.presetId != null ? ', presetId = "${_escapeString(fx.presetId!)}"' : '';
        final scriptStr = fx.luaScriptCode != null && fx.luaScriptCode!.isNotEmpty ? ', luaScriptCode = ${_formatLuaString(fx.luaScriptCode!, '  ')}' : '';
        final luaParamsStr = fx.luaParams.isNotEmpty ? ', luaParams = ${_formatMap(fx.luaParams)}' : '';
        buffer.writeln('    { id = "${_escapeString(fx.id)}", name = "${_escapeString(fx.name)}", type = "${fx.type.name}", enabled = ${fx.enabled}, mix = ${fx.mix.toStringAsFixed(2)}, params = ${_formatMap(fx.params)}$irStr$presetStr$scriptStr$luaParamsStr },');
      }
      buffer.writeln('  },');
    }
    buffer.writeln('}');

    return buffer.toString();
  }

  /// Serializes a list of [Note] objects into a self-contained `.lua` snippet
  /// suitable for clipboard export and external Lua scripting.
  static String serializeNotes(List<Note> notes, {bool relativeSteps = true}) {
    if (notes.isEmpty) return 'return {}';
    final double minStep = relativeSteps
        ? notes.map((n) => n.startStep).reduce((a, b) => a < b ? a : b)
        : 0.0;
    final int minCol = relativeSteps
        ? notes.map((n) => n.column).reduce((a, b) => a < b ? a : b)
        : 0;

    final buffer = StringBuffer();
    buffer.writeln('-- Eatsbeats Notes (${notes.length} note${notes.length > 1 ? 's' : ''})');
    buffer.writeln('return {');
    for (final n in notes) {
      final relStep = (n.startStep - minStep).clamp(0.0, double.infinity);
      final relCol = (n.column - minCol).clamp(0, 16);
      final extra = _formatNoteExpressiveProps(n);
      buffer.writeln('  { pitch = ${n.pitch}, startStep = ${relStep.toStringAsFixed(2)}, durationSteps = ${n.durationSteps.toStringAsFixed(2)}, velocity = ${n.velocity.toStringAsFixed(2)}, column = $relCol, effectCommand = "${_escapeString(n.effectCommand)}", isSlide = ${n.isSlide}, isAccent = ${n.isAccent}$extra },');
    }
    buffer.writeln('}');
    return buffer.toString();
  }

  static String _formatCurvePoints(List<List<double>> points) {
    final inner = points.map((p) => '{ ${p.map((v) => v.toStringAsFixed(2)).join(', ')} }').join(', ');
    return '{ $inner }';
  }

  static String _formatNoteExpressiveProps(Note n) {
    final buffer = StringBuffer();
    if (n.lyric != null && n.lyric!.isNotEmpty) {
      buffer.write(', lyric = "${_escapeString(n.lyric!)}"');
    }
    if (n.articulation != null && n.articulation!.isNotEmpty) {
      buffer.write(', art = "${_escapeString(n.articulation!)}"');
    }
    if (n.releaseVelocity != null) {
      buffer.write(', relVel = ${n.releaseVelocity!.toStringAsFixed(2)}');
    }
    if (n.pitchBendPoints != null && n.pitchBendPoints!.isNotEmpty) {
      buffer.write(', bend = ${_formatCurvePoints(n.pitchBendPoints!)}');
    }
    if (n.pressurePoints != null && n.pressurePoints!.isNotEmpty) {
      buffer.write(', pressure = ${_formatCurvePoints(n.pressurePoints!)}');
    }
    if (n.timbrePoints != null && n.timbrePoints!.isNotEmpty) {
      buffer.write(', timbre = ${_formatCurvePoints(n.timbrePoints!)}');
    }
    return buffer.toString();
  }

  static void _serializeTrack(StringBuffer buffer, TrackChannel track, {required String indent}) {
    buffer.writeln('$indent{');
    final childIndent = '$indent  ';

    buffer.writeln('${childIndent}id = "${_escapeString(track.id)}",');
    buffer.writeln('${childIndent}name = "${_escapeString(track.name)}",');
    buffer.writeln('${childIndent}color = 0x${track.color.value.toRadixString(16).padLeft(8, '0')},');
    buffer.writeln('${childIndent}type = "${track.type.name}",');
    buffer.writeln('${childIndent}volume = ${track.volume.toStringAsFixed(3)},');
    buffer.writeln('${childIndent}pan = ${track.pan.toStringAsFixed(3)},');
    buffer.writeln('${childIndent}isMuted = ${track.isMuted},');
    buffer.writeln('${childIndent}isSoloed = ${track.isSoloed},');
    buffer.writeln('${childIndent}chordFollowMode = "${track.chordFollowMode.name}",');

    if (track.tags.isNotEmpty) {
      final tagsStr = track.tags.map((t) => '"${_escapeString(t)}"').join(', ');
      buffer.writeln('${childIndent}tags = { $tagsStr },');
    }

    if (track.eqEnabled || track.eqLowGain != 0.0 || track.eqMidGain != 0.0 || track.eqHighGain != 0.0 || track.eqHpf > 20.0) {
      buffer.writeln('${childIndent}eq = {');
      buffer.writeln('$childIndent  enabled = ${track.eqEnabled},');
      buffer.writeln('$childIndent  hpf = ${track.eqHpf.toStringAsFixed(1)},');
      buffer.writeln('$childIndent  lowGain = ${track.eqLowGain.toStringAsFixed(2)},');
      buffer.writeln('$childIndent  midFreq = ${track.eqMidFreq.toStringAsFixed(1)},');
      buffer.writeln('$childIndent  midGain = ${track.eqMidGain.toStringAsFixed(2)},');
      buffer.writeln('$childIndent  midQ = ${track.eqMidQ.toStringAsFixed(2)},');
      buffer.writeln('$childIndent  highGain = ${track.eqHighGain.toStringAsFixed(2)},');
      buffer.writeln('${childIndent}},');
    }

    // Instrument parameters
    buffer.writeln('${childIndent}sampleName = "${_escapeString(track.sampleName)}",');
    buffer.writeln('${childIndent}synthWaveform = "${_escapeString(track.synthWaveform)}",');
    buffer.writeln('${childIndent}cutoff = ${track.cutoff.toStringAsFixed(1)},');
    buffer.writeln('${childIndent}resonance = ${track.resonance.toStringAsFixed(2)},');
    buffer.writeln('${childIndent}attack = ${track.attack.toStringAsFixed(3)},');
    buffer.writeln('${childIndent}release = ${track.release.toStringAsFixed(3)},');
    buffer.writeln('${childIndent}trackerColumns = ${track.trackerColumns},');
    buffer.writeln('${childIndent}activeView = "${track.activeView.name}",');

    // Lua plugin script & params
    if (track.luaScriptCode.isNotEmpty) {
      buffer.writeln('${childIndent}luaScriptCode = ${_formatLuaString(track.luaScriptCode, childIndent)},');
    }
    if (track.luaParams.isNotEmpty) {
      buffer.writeln('${childIndent}luaParams = {');
      track.luaParams.forEach((key, val) {
        buffer.writeln('$childIndent  ["${_escapeString(key)}"] = ${val.toStringAsFixed(4)},');
      });
      buffer.writeln('${childIndent}},');
    }

    // Step sequencer events
    final activeSteps = <int, StepEvent>{};
    for (int i = 0; i < track.steps.length; i++) {
      if (track.steps[i].active) {
        activeSteps[i] = track.steps[i];
      }
    }
    if (activeSteps.isNotEmpty) {
      buffer.writeln('${childIndent}steps = {');
      activeSteps.forEach((stepIdx, step) {
        buffer.writeln('$childIndent  [${stepIdx + 1}] = { pitch = ${step.pitch}, velocity = ${step.velocity.toStringAsFixed(2)}, isSlide = ${step.isSlide}, isAccent = ${step.isAccent} },');
      });
      buffer.writeln('${childIndent}},');
    }

    // Piano Roll Notes
    if (track.notes.isNotEmpty) {
      buffer.writeln('${childIndent}notes = {');
      for (final n in track.notes) {
        final extra = _formatNoteExpressiveProps(n);
        buffer.writeln('$childIndent  { id = "${_escapeString(n.id)}", pitch = ${n.pitch}, startStep = ${n.startStep.toStringAsFixed(2)}, durationSteps = ${n.durationSteps.toStringAsFixed(2)}, velocity = ${n.velocity.toStringAsFixed(2)}, column = ${n.column}, effectCommand = "${_escapeString(n.effectCommand)}", isSlide = ${n.isSlide}, isAccent = ${n.isAccent}$extra },');
      }
      buffer.writeln('${childIndent}},');
    }

    // Clips
    if (track.clips.isNotEmpty) {
      buffer.writeln('${childIndent}clips = {');
      for (final clip in track.clips) {
        _serializeClip(buffer, clip, indent: '$childIndent  ');
      }
      buffer.writeln('${childIndent}},');
    }

    // FX Racks
    if (track.fxRack.isNotEmpty) {
      buffer.writeln('${childIndent}fxRack = {');
      for (final fx in track.fxRack) {
        final irStr = fx.irSampleName != null ? ', irSampleName = "${_escapeString(fx.irSampleName!)}"' : '';
        final presetStr = fx.presetId != null ? ', presetId = "${_escapeString(fx.presetId!)}"' : '';
        final scriptStr = fx.luaScriptCode != null && fx.luaScriptCode!.isNotEmpty ? ', luaScriptCode = ${_formatLuaString(fx.luaScriptCode!, childIndent)}' : '';
        final luaParamsStr = fx.luaParams.isNotEmpty ? ', luaParams = ${_formatMap(fx.luaParams)}' : '';
        buffer.writeln('$childIndent  { id = "${_escapeString(fx.id)}", name = "${_escapeString(fx.name)}", type = "${fx.type.name}", enabled = ${fx.enabled}, mix = ${fx.mix.toStringAsFixed(2)}, params = ${_formatMap(fx.params)}$irStr$presetStr$scriptStr$luaParamsStr },');
      }
      buffer.writeln('${childIndent}},');
    }

    // MIDI FX Racks
    if (track.midiFXRack.isNotEmpty) {
      buffer.writeln('${childIndent}midiFXRack = {');
      for (final mfx in track.midiFXRack) {
        buffer.writeln('$childIndent  { id = "${_escapeString(mfx.id)}", name = "${_escapeString(mfx.name)}", enabled = ${mfx.enabled}, luaScriptCode = ${_formatLuaString(mfx.luaScriptCode, childIndent)}, luaParams = ${_formatMap(mfx.luaParams)} },');
      }
      buffer.writeln('${childIndent}},');
    }

    buffer.writeln('$indent},');
  }

  static void _serializeClip(StringBuffer buffer, TrackClip clip, {required String indent}) {
    buffer.writeln('$indent{');
    final childIndent = '$indent  ';
    buffer.writeln('${childIndent}id = "${_escapeString(clip.id)}",');
    buffer.writeln('${childIndent}name = "${_escapeString(clip.name)}",');
    buffer.writeln('${childIndent}trackId = "${_escapeString(clip.trackId)}",');
    buffer.writeln('${childIndent}startBar = ${clip.startBar},');
    buffer.writeln('${childIndent}barLength = ${clip.barLength},');
    buffer.writeln('${childIndent}patternIndex = ${clip.patternIndex},');
    if (clip.loopLengthBars != null) {
      buffer.writeln('${childIndent}loopLengthBars = ${clip.loopLengthBars},');
    }
    if (clip.isAudioClip) {
      buffer.writeln('${childIndent}isAudioClip = true,');
    }
    if (clip.audioSampleName != null && clip.audioSampleName!.isNotEmpty) {
      buffer.writeln('${childIndent}audioSampleName = "${_escapeString(clip.audioSampleName!)}",');
    }
    if (clip.audioPitchOffset != 0.0) {
      buffer.writeln('${childIndent}audioPitchOffset = ${clip.audioPitchOffset.toStringAsFixed(2)},');
    }

    if (clip.luaScriptCode.isNotEmpty) {
      buffer.writeln('${childIndent}luaScriptCode = ${_formatLuaString(clip.luaScriptCode, childIndent)},');
    }
    if (clip.luaParams.isNotEmpty) {
      buffer.writeln('${childIndent}luaParams = ${_formatMap(clip.luaParams)},');
    }

    if (clip.lyrics.isNotEmpty) {
      buffer.writeln('${childIndent}lyrics = {');
      for (final l in clip.lyrics) {
        buffer.writeln('$childIndent  { id = "${_escapeString(l.id)}", text = "${_escapeString(l.text)}", startStep = ${l.startStep.toStringAsFixed(2)}, durationSteps = ${l.durationSteps.toStringAsFixed(2)} },');
      }
      buffer.writeln('${childIndent}},');
    }

    if (clip.automationLanes.isNotEmpty) {
      buffer.writeln('${childIndent}automationLanes = {');
      for (final lane in clip.automationLanes) {
        buffer.writeln('$childIndent  { id = "${_escapeString(lane.id)}", targetId = "${_escapeString(lane.target.id)}", targetName = "${_escapeString(lane.target.name)}", enabled = ${lane.enabled}, points = {');
        for (final pt in lane.points) {
          buffer.writeln('$childIndent    { id = "${_escapeString(pt.id)}", step = ${pt.step.toStringAsFixed(2)}, value = ${pt.value.toStringAsFixed(4)}, easing = "${pt.easing.name}", tension = ${pt.tension.toStringAsFixed(2)} },');
        }
        buffer.writeln('$childIndent  } },');
      }
      buffer.writeln('${childIndent}},');
    }

    if (clip.notes.isNotEmpty) {
      buffer.writeln('${childIndent}notes = {');
      for (final n in clip.notes) {
        final extra = _formatNoteExpressiveProps(n);
        buffer.writeln('$childIndent  { id = "${_escapeString(n.id)}", pitch = ${n.pitch}, startStep = ${n.startStep.toStringAsFixed(2)}, durationSteps = ${n.durationSteps.toStringAsFixed(2)}, velocity = ${n.velocity.toStringAsFixed(2)}, column = ${n.column}, effectCommand = "${_escapeString(n.effectCommand)}", isSlide = ${n.isSlide}, isAccent = ${n.isAccent}$extra },');
      }
      buffer.writeln('${childIndent}},');
    }
    buffer.writeln('$indent},');
  }

  static String _escapeString(String str) {
    return str
        .replaceAll('\\', '\\\\')
        .replaceAll('"', '\\"')
        .replaceAll('\n', '\\n')
        .replaceAll('\r', '\\r');
  }

  static String _formatLuaString(String str, String indent) {
    if (!str.contains('\n') && !str.contains('"')) {
      return '"${_escapeString(str)}"';
    }
    if (!str.contains(']]')) {
      return '[[\n$str\n$indent]]';
    }
    return '[=[\n$str\n$indent]=]';
  }

  static String _formatMap(Map<String, double> map) {
    if (map.isEmpty) return '{}';
    final parts = map.entries.map((e) => '["${_escapeString(e.key)}"] = ${e.value.toStringAsFixed(4)}').join(', ');
    return '{ $parts }';
  }
}
