import 'dart:io';

void main(List<String> args) {
  final stopwatch = Stopwatch()..start();
  final presetsDir = Directory('presets');
  if (!presetsDir.existsSync()) {
    stderr.writeln('Error: presets/ directory not found in ${Directory.current.path}');
    exit(1);
  }

  print('Scanning presets/ for .eat files...');
  final files = presetsDir
      .listSync(recursive: true)
      .whereType<File>()
      .where((f) => f.path.endsWith('.eat'))
      .toList();

  print('Found ${files.length} preset files.');

  final List<ParsedPreset> presets = [];
  final Set<String> seenIds = {};

  for (final file in files) {
    final content = file.readAsStringSync();
    final parsed = parsePreset(content, file.path);
    if (seenIds.contains(parsed.id)) {
      print('Warning: Duplicate preset id "${parsed.id}" in ${file.path}, skipping.');
      continue;
    }
    seenIds.add(parsed.id);
    presets.add(parsed);
  }

  // Sort deterministically by category then ID
  presets.sort((a, b) {
    final catComp = a.category.compareTo(b.category);
    if (catComp != 0) return catComp;
    return a.id.compareTo(b.id);
  });

  print('Bundling ${presets.length} presets into lib/eatscript/eat_builtin_presets.g.dart...');

  final buffer = StringBuffer();
  buffer.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
  buffer.writeln('// Generated by: dart run tool/bundle_presets.dart');
  buffer.writeln('// Presets count: ${presets.length}');
  buffer.writeln();
  buffer.writeln("import 'eat_script_library.dart';");
  buffer.writeln();
  buffer.writeln('class EatBuiltinPresets {');
  buffer.writeln('  static const List<EatScriptDef> presets = [');

  for (final p in presets) {
    buffer.writeln('    EatScriptDef(');
    buffer.writeln("      id: '${escapeDartString(p.id)}',");
    buffer.writeln("      name: '${escapeDartString(p.name)}',");
    buffer.writeln('      category: EatScriptCategory.${p.category},');
    buffer.writeln("      description: '${escapeDartString(p.description)}',");
    if (p.tags.isNotEmpty) {
      final tagsStr = p.tags.map((t) => "'${escapeDartString(t)}'").join(', ');
      buffer.writeln('      tags: [$tagsStr],');
    }
    buffer.writeln("      code: r'''");
    buffer.writeln(p.code);
    buffer.writeln("''',");
    buffer.writeln('    ),');
  }

  buffer.writeln('  ];');
  buffer.writeln();
  buffer.writeln('  static final Map<String, EatScriptDef> _byId = {');
  buffer.writeln('    for (final p in presets) p.id: p,');
  buffer.writeln('  };');
  buffer.writeln();
  buffer.writeln('  static EatScriptDef? getById(String id) => _byId[id];');
  buffer.writeln('}');
  buffer.writeln();

  final outFile = File('lib/eatscript/eat_builtin_presets.g.dart');
  outFile.writeAsStringSync(buffer.toString());

  stopwatch.stop();
  print('Successfully generated ${outFile.path} in ${stopwatch.elapsedMilliseconds}ms.');
}

class ParsedPreset {
  final String id;
  final String name;
  final String category;
  final String description;
  final List<String> tags;
  final String code;

  ParsedPreset({
    required this.id,
    required this.name,
    required this.category,
    required this.description,
    required this.tags,
    required this.code,
  });
}

ParsedPreset parsePreset(String rawContent, String filePath) {
  final lines = rawContent.split('\n');
  String? id;
  String? name;
  String categoryStr = 'instrument';
  String description = '';
  final List<String> tags = [];

  for (final line in lines) {
    final trimmed = line.trim();
    final clean = trimmed.startsWith('#')
        ? trimmed.substring(1).trim()
        : (trimmed.startsWith('--') ? trimmed.substring(2).trim() : trimmed);

    if (clean.startsWith('@id:')) {
      id = clean.substring(4).trim();
    } else if (clean.startsWith('@name:')) {
      name = clean.substring(6).trim();
    } else if (clean.startsWith('@category:')) {
      categoryStr = clean.substring(10).trim();
    } else if (clean.startsWith('@description:')) {
      description = clean.substring(13).trim();
    } else if (clean.startsWith('@tags:') || clean.startsWith('@tag:')) {
      final prefixLen = clean.startsWith('@tags:') ? 6 : 5;
      final rawTags = clean.substring(prefixLen).split(',');
      for (final t in rawTags) {
        final ct = t.trim().toLowerCase();
        if (ct.isNotEmpty && !tags.contains(ct)) tags.add(ct);
      }
    }
  }

  // Fallback if metadata header missing
  final fileBasename = filePath.replaceAll('\\', '/').split('/').last.replaceAll('.eat', '');
  id ??= fileBasename;
  name ??= fileBasename
      .split('_')
      .map((w) => w.isNotEmpty ? '${w[0].toUpperCase()}${w.substring(1)}' : '')
      .join(' ');

  // Normalize category enum name
  String categoryEnum;
  final cleanCat = categoryStr.toLowerCase().replaceAll(RegExp(r'[^a-z0-9]'), '');
  if (cleanCat == 'projectaction' || cleanCat.contains('action')) {
    categoryEnum = 'projectAction';
  } else if (cleanCat == 'utility' || cleanCat == 'util') {
    categoryEnum = 'utility';
  } else if (cleanCat == 'macro') {
    categoryEnum = 'macro';
  } else if (cleanCat.contains('notesplitter') || cleanCat.contains('split')) {
    categoryEnum = 'noteSplitter';
  } else if (cleanCat.contains('midiseq') || cleanCat.contains('seq')) {
    categoryEnum = 'midiSeq';
  } else if (cleanCat.contains('midifx')) {
    categoryEnum = 'midiFx';
  } else if (cleanCat.contains('audiofx') || cleanCat.contains('effect') || (cleanCat.contains('fx') && !cleanCat.contains('midi'))) {
    categoryEnum = 'audioFx';
  } else {
    categoryEnum = 'instrument';
  }

  // Clean any accidental markdown code fences or backticks
  var safeCode = rawContent.trim();
  while (safeCode.startsWith('```')) {
    safeCode = safeCode.replaceFirst(RegExp(r'^```[a-zA-Z]*\s*\r?\n?'), '').trim();
  }
  while (safeCode.endsWith('```')) {
    safeCode = safeCode.replaceFirst(RegExp(r'\r?\n?```\s*$'), '').trim();
  }

  // Safely escape any triple single-quotes in the code
  safeCode = safeCode.replaceAll("'''", r"'\''");

  return ParsedPreset(
    id: id,
    name: name,
    category: categoryEnum,
    description: description,
    tags: tags,
    code: safeCode,
  );
}

String escapeDartString(String s) {
  return s.replaceAll(r'\', r'\\').replaceAll("'", r"\'");
}
