-- Eatsbeats Song File: "Eats Volts"
-- Generated by Eatsbeats DAW

return eatsbeats.song {
  version = "1.0",
  meta = {
    title = "Eats Volts",
    author = "Eatsbits",
    songKey = "C Major",
    bpm = 124.00,
    masterVolume = 0.85,
    isSongMode = false,
    isLooping = true,
    loopStartBar = 0,
    loopEndBar = 2,
    masterLimiter = {
      enabled = true,
      ceilingDbfs = -0.30,
      driveDb = 0.00,
      targetLufs = -14.0,
    },
  },

  patterns = {
    {
      id = "p0",
      name = "Pattern A",
      lengthSteps = 16,
      tracks = {
        {
          id = "t_kick",
          name = "Eats Kick",
          color = 0xffff007a,
          type = "luaScript",
          volume = 0.950,
          pan = 0.000,
          isMuted = true,
          isSoloed = false,
          chordFollowMode = "off",
          sampleName = "kick",
          synthWaveform = "sawtooth",
          cutoff = 3000.0,
          resonance = 1.00,
          attack = 0.010,
          release = 0.300,
          trackerColumns = 4,
          activeView = "pianoRoll",
          luaScriptCode = [[
-- @name: Eats Kick
-- @category: instrument
local ProceduralKick = {}

function ProceduralKick.init()
  Param.add("StartFreq", 100.0, 300.0, 160.0)
  Param.add("EndFreq", 30.0, 60.0, 42.0)
  Param.add("PitchDecay", 0.01, 0.1, 0.035)
  Param.add("AmpDecay", 0.1, 0.6, 0.35)
  Param.add("Click", 0.0, 1.0, 0.0)
end

function ProceduralKick.process(time, freq, note, params)
  local startF = params["StartFreq"] or 160.0
  local endF = params["EndFreq"] or 42.0
  local pDecay = params["PitchDecay"] or 0.035
  local aDecay = params["AmpDecay"] or 0.35
  local click = params["Click"] or 0.0

  local curFreq = endF + (startF - endF) * math.exp(-time / math.max(0.005, pDecay))
  local phase = 2.0 * math.pi * curFreq * time
  local subSine = math.sin(phase)

  local clickTransient = (math.random() * 2.0 - 1.0) * math.exp(-time * 150.0) * click
  local env = math.exp(-time * 5.0 / math.max(0.01, aDecay))
  local rawOutput = (subSine * 0.85 + clickTransient * 0.15) * env

  local maxDur = math.max(0.1, aDecay)
  local fadeStart = maxDur - 0.04
  local edgeFade = 1.0
  if time > fadeStart then
    local norm = math.max(0.0, math.min(1.0, (maxDur - time) / 0.04))
    edgeFade = 0.5 * (1.0 - math.cos(math.pi * norm))
  end
  if time >= maxDur then edgeFade = 0.0 end
  return math.tanh(rawOutput * edgeFade * 1.3)
end

function ProceduralKick.rack()
  return {
    rows = {
      -- ROW 1
      {
        { id = "exciter", title = "NOISE FM EXCITER", hp = 11, row = 1, category = "MOD" },
        { id = "carrier", title = "BATTER CARRIER VCO", hp = 15, row = 1, category = "VCO" },
        { id = "sub_eq", title = "SUB PEAKING EQ", hp = 11, row = 1, category = "VCF" },
      },
      -- ROW 2
      {
        { id = "room_vco", title = "ROOM FARFIELD VCO", hp = 11, row = 2, category = "VCO" },
        { id = "delay", title = "ROOM DELAY LINE", hp = 14, row = 2, category = "FX" },
        { id = "master", title = "MASTER DUAL-MIC OUT", hp = 15, row = 2, category = "OUT" },
      },
    },
    cables = {
      { from = "1:0:1", to = "1:1:0", color = "modulation" },
      { from = "1:1:2", to = "1:2:0", color = "audio" },
      { from = "1:2:1", to = "2:2:0", color = "audio" },
      { from = "2:0:1", to = "2:1:0", color = "pitch" },
      { from = "2:1:1", to = "2:2:1", color = "pitch" },
    }
  }
end

return ProceduralKick
          ]],
          luaParams = {
            ["StartFreq"] = 134.3804,
            ["EndFreq"] = 60.0000,
            ["PitchDecay"] = 0.0630,
            ["AmpDecay"] = 0.6000,
            ["Click"] = 0.0646,
          },
          steps = {
            [1] = { pitch = 36, velocity = 0.95, isSlide = false, isAccent = true },
            [2] = { pitch = 36, velocity = 0.95, isSlide = false, isAccent = true },
            [3] = { pitch = 36, velocity = 0.95, isSlide = false, isAccent = true },
            [4] = { pitch = 36, velocity = 0.95, isSlide = false, isAccent = true },
            [5] = { pitch = 36, velocity = 0.95, isSlide = false, isAccent = true },
            [6] = { pitch = 36, velocity = 0.95, isSlide = false, isAccent = true },
            [7] = { pitch = 36, velocity = 0.95, isSlide = false, isAccent = true },
            [8] = { pitch = 36, velocity = 0.95, isSlide = false, isAccent = true },
          },
          notes = {
            { id = "n_clip_c_k1_b0_0", pitch = 36, startStep = 0.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "n_clip_c_k1_b0_4", pitch = 36, startStep = 4.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "n_clip_c_k1_b0_8", pitch = 36, startStep = 8.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "n_clip_c_k1_b0_12", pitch = 36, startStep = 12.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "n_clip_c_k1_b1_0", pitch = 36, startStep = 16.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "n_clip_c_k1_b1_4", pitch = 36, startStep = 20.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "n_clip_c_k1_b1_8", pitch = 36, startStep = 24.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "n_clip_c_k1_b1_12", pitch = 36, startStep = 28.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "n_clip_c_k1_b2_0", pitch = 36, startStep = 32.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "n_clip_c_k1_b2_4", pitch = 36, startStep = 36.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "n_clip_c_k1_b2_8", pitch = 36, startStep = 40.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "n_clip_c_k1_b2_12", pitch = 36, startStep = 44.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "n_clip_c_k1_b3_0", pitch = 36, startStep = 48.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "n_clip_c_k1_b3_4", pitch = 36, startStep = 52.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "n_clip_c_k1_b3_8", pitch = 36, startStep = 56.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "n_clip_c_k1_b3_12", pitch = 36, startStep = 60.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
          },
          clips = {
            {
              id = "c_k1",
              name = "4-to-Floor Kick",
              trackId = "t_kick",
              startBar = 0,
              barLength = 4,
              luaScriptCode = [[
-- @name: 4-to-Floor Kick
-- @category: midiSeq
-- @description: Classic 4-on-the-floor kick pattern for house/techno/EDM

notes = {
  { pitch = 36, start = 0.00, duration = 1.00, vel = 0.95 },
  { pitch = 36, start = 4.00, duration = 1.00, vel = 0.90 },
  { pitch = 36, start = 8.00, duration = 1.00, vel = 0.95 },
  { pitch = 36, start = 12.00, duration = 1.00, vel = 0.90 }
}

function process(notes, time_ctx)
  return notes
end
              ]],
              notes = {
                { id = "n_clip_c_k1_b0_0", pitch = 36, startStep = 0.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "n_clip_c_k1_b0_4", pitch = 36, startStep = 4.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "n_clip_c_k1_b0_8", pitch = 36, startStep = 8.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "n_clip_c_k1_b0_12", pitch = 36, startStep = 12.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "n_clip_c_k1_b1_0", pitch = 36, startStep = 16.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "n_clip_c_k1_b1_4", pitch = 36, startStep = 20.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "n_clip_c_k1_b1_8", pitch = 36, startStep = 24.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "n_clip_c_k1_b1_12", pitch = 36, startStep = 28.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "n_clip_c_k1_b2_0", pitch = 36, startStep = 32.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "n_clip_c_k1_b2_4", pitch = 36, startStep = 36.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "n_clip_c_k1_b2_8", pitch = 36, startStep = 40.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "n_clip_c_k1_b2_12", pitch = 36, startStep = 44.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "n_clip_c_k1_b3_0", pitch = 36, startStep = 48.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "n_clip_c_k1_b3_4", pitch = 36, startStep = 52.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "n_clip_c_k1_b3_8", pitch = 36, startStep = 56.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "n_clip_c_k1_b3_12", pitch = 36, startStep = 60.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
              },
            },
          },
        },
        {
          id = "track_1788123004462",
          name = "Eats Volts",
          color = 0xff00ff66,
          type = "luaScript",
          volume = 0.800,
          pan = 0.000,
          isMuted = false,
          isSoloed = false,
          chordFollowMode = "bass",
          tags = { "synth_lead", "lead", "presence_bite", "hpf_safe_100hz" },
          sampleName = "",
          synthWaveform = "sawtooth",
          cutoff = 3000.0,
          resonance = 1.00,
          attack = 0.010,
          release = 0.300,
          trackerColumns = 4,
          activeView = "pianoRoll",
          luaScriptCode = [[
-- @id: eats_volts
-- @name: Eats Volts
-- @category: instrument
-- @description: Physical modeling of real-world electricity, singing plasma arcs, and high-voltage discharge: asymmetric thermal expansion pulse oscillator, cycle-to-cycle spark jitter, Poisson-distributed corona sizzle, 60Hz substation transformer magnetostriction hum, dielectric breakdown attack snap, spark gap acoustic cavity formants, 4-stage plasma vortex phaser, and ozone saturation.

local EatsVolts = {}

function EatsVolts.init()
  -- Plasma Arc & Discharge Core
  Param.add("Voltage", 0.1, 3.0, 1.25)
  Param.add("SparkGap", 0.02, 0.50, 0.15)
  Param.add("Jitter", 0.0, 1.0, 0.45)
  Param.add("SubHarmonic", 0.0, 1.0, 0.20)

  -- Corona Ionization & Dielectric Breakdown
  Param.add("CrackleRate", 0.0, 1.0, 0.40)
  Param.add("SnapAttack", 0.0, 2.5, 1.0)
  Param.add("GridHum", 0.0, 1.0, 0.35)

  -- Plasma Vortex All-Pass Phaser
  Param.add("PhaserRate", 0.05, 8.0, 0.45)
  Param.add("PhaserDepth", 0.0, 1.0, 0.65)
  Param.add("PhaserFeedback", 0.0, 1.0, 0.40)
  Param.add("PhaserMix", 0.0, 1.0, 0.45)

  -- Ozone Saturation & Gas Tone Shaping
  Param.add("OzoneDrive", 0.5, 5.0, 1.35)
  Param.add("ToneHighpass", 20.0, 2000.0, 30.0)
  Param.add("Tone", 1000.0, 16000.0, 8500.0)
  Param.add("Decay", 0.05, 2.0, 0.45)
end

function EatsVolts.process(time, freq, note, params)
  local voltage = params["Voltage"] or 1.25
  local gap = params["SparkGap"] or 0.15
  local jitter = params["Jitter"] or 0.45
  local crackle = params["CrackleRate"] or 0.40
  local snap = params["SnapAttack"] or 1.0
  local hum = params["GridHum"] or 0.35
  local drive = params["OzoneDrive"] or 1.35
  local decay = params["Decay"] or 0.45
  local pRate = params["PhaserRate"] or 0.45
  local pDepth = params["PhaserDepth"] or 0.65
  local pMix = params["PhaserMix"] or 0.45

  -- Direct single-cycle fallback
  local fInst = freq * (1.0 + (math.random() * 2.0 - 1.0) * jitter * 0.03)
  local phase = (fInst * time) % 1.0
  local arcPulse = (phase < gap) and math.sin(phase / gap * math.pi) or (-0.3 * math.exp(-(phase - gap) * 6.0))

  -- 60Hz Substation hum
  local humTone = math.sin(2.0 * math.pi * 60.0 * time) * 0.5 + math.sin(2.0 * math.pi * 180.0 * time) * 0.25

  -- Dielectric snap
  local snapTransient = (math.random() * 2.0 - 1.0) * math.exp(-time * 250.0) * snap

  -- Corona crackle
  local microSpark = (math.random() < (crackle * 0.08)) and ((math.random() * 2.0 - 1.0) * 0.6) or 0.0

  -- Phaser modulation fallback
  local phaserMod = 1.0 + 0.3 * pMix * math.sin(2.0 * math.pi * pRate * time) * pDepth

  local ampEnv = math.exp(-time / math.max(0.04, decay))
  local raw = (arcPulse * voltage * phaserMod + humTone * hum + snapTransient + microSpark) * ampEnv

  return math.tanh(raw * drive) * 0.95
end

function EatsVolts.gui()
  return {
    panel = {
      title = "EATS VOLTS",
      subtitle = "High-Voltage Plasma Synthesizer",
      accent = "#00F0FF",
      background = "matte_metal",
      rackSides = "brushed_steel",
      cornerRadius = 0,
      layout = {
        -- CYAN SECTION: Singing Plasma Arc & Spark Gap
        {
          type = "group",
          label = "PLASMA DISCHARGE & ARC CORE (CYAN)",
          accent = "#00F0FF",
          children = {
            {
              type = "row",
              children = {
                { type = "knob", param = "Voltage", label = "VOLTAGE", unit = "kV", knobStyle = "chrome", size = 52 },
                { type = "knob", param = "SparkGap", label = "SPARK GAP", unit = "mm", knobStyle = "chrome", size = 52 },
                { type = "knob", param = "Jitter", label = "ARC JITTER", unit = "%", knobStyle = "chrome", size = 52 },
                { type = "knob", param = "SubHarmonic", label = "SUB-PLASMA", unit = "%", knobStyle = "chrome", size = 52 },
              }
            }
          }
        },
        -- AMBER SECTION: Corona Sizzle & Breakdown Snap
        {
          type = "group",
          label = "CORONA SIZZLE & DIELECTRIC SNAP (AMBER)",
          accent = "#FFB300",
          children = {
            {
              type = "row",
              children = {
                { type = "knob", param = "CrackleRate", label = "CORONA SIZZLE", unit = "%", knobStyle = "vintage", size = 52 },
                { type = "knob", param = "SnapAttack", label = "SNAP STRIKE", knobStyle = "vintage", size = 52 },
                { type = "knob", param = "GridHum", label = "60Hz HUM", unit = "dB", knobStyle = "vintage", size = 52 },
              }
            },
            {
              type = "row",
              children = {
                { type = "hslider", param = "Voltage", label = "HIGH-VOLTAGE RAIL POTENTIAL", style = "capsule" },
              }
            }
          }
        },
        -- PURPLE SECTION: Plasma Vortex Phaser
        {
          type = "group",
          label = "PLASMA VORTEX PHASER (PURPLE)",
          accent = "#7C4DFF",
          children = {
            {
              type = "row",
              children = {
                { type = "knob", param = "PhaserRate", label = "PHASER RATE", unit = "Hz", knobStyle = "vintage", size = 52 },
                { type = "knob", param = "PhaserDepth", label = "SWEEP DEPTH", unit = "%", knobStyle = "vintage", size = 52 },
                { type = "knob", param = "PhaserFeedback", label = "VORTEX RESO", unit = "%", knobStyle = "vintage", size = 52 },
                { type = "knob", param = "PhaserMix", label = "PHASER MIX", unit = "%", knobStyle = "vintage", size = 52 },
              }
            }
          }
        },
        -- MAGENTA SECTION: Ozone Saturation & Gas Tone
        {
          type = "group",
          label = "OZONE SATURATION & GAS TONE (MAGENTA)",
          accent = "#E040FB",
          children = {
            {
              type = "row",
              children = {
                { type = "knob", param = "OzoneDrive", label = "OZONE DRIVE", knobStyle = "vintage", size = 52 },
                { type = "knob", param = "ToneHighpass", label = "LOW CUT", unit = "Hz", knobStyle = "vintage", size = 52 },
                { type = "knob", param = "Tone", label = "HIGH CUT", unit = "Hz", knobStyle = "vintage", size = 52 },
                { type = "knob", param = "Decay", label = "ARC DECAY", unit = "s", knobStyle = "vintage", size = 52 },
              }
            }
          }
        }
      }
    }
  }
end

function EatsVolts.rack()
  return {
    rows = {
      {
        { id = "plasma_osc",    title = "SINGING ARC OSCILLATOR", hp = 16, row = 1, category = "VCO" },
        { id = "corona_crackle",title = "POISSON CORONA SIZZLE",  hp = 14, row = 1, category = "MOD" },
      },
      {
        { id = "spark_formants",title = "SPARK GAP RESONATOR",    hp = 16, row = 2, category = "VCF" },
        { id = "master_out",    title = "OZONE SATURATION OUT",   hp = 14, row = 2, category = "OUT" },
      },
    },
    cables = {
      { from = "1:0:1", to = "2:0:0", color = "audio" },
      { from = "1:1:1", to = "2:0:0", color = "cv" },
      { from = "2:0:1", to = "2:1:0", color = "audio" },
    }
  }
end

return EatsVolts

          ]],
          luaParams = {
            ["Voltage"] = 1.2500,
            ["SparkGap"] = 0.1500,
            ["Jitter"] = 0.4500,
            ["SubHarmonic"] = 0.2000,
            ["CrackleRate"] = 0.4000,
            ["SnapAttack"] = 1.0000,
            ["GridHum"] = 0.3500,
            ["PhaserRate"] = 0.4500,
            ["PhaserDepth"] = 0.6500,
            ["PhaserFeedback"] = 0.4000,
            ["PhaserMix"] = 0.4500,
            ["OzoneDrive"] = 1.3500,
            ["ToneHighpass"] = 30.0000,
            ["Tone"] = 8500.0000,
            ["Decay"] = 0.4500,
          },
          notes = {
            { id = "1788123010417", pitch = 36, startStep = 0.00, durationSteps = 16.00, velocity = 0.85, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "1788123051051", pitch = 36, startStep = 16.00, durationSteps = 16.00, velocity = 0.85, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
          },
          clips = {
            {
              id = "clip_track_1788123004462_0",
              name = "VOLTAIC: High-Voltage Plasma Synthesizer",
              trackId = "track_1788123004462",
              startBar = 0,
              barLength = 4,
              loopLengthBars = 2,
              notes = {
                { id = "1788123010417", pitch = 36, startStep = 0.00, durationSteps = 16.00, velocity = 0.85, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "1788123051051", pitch = 36, startStep = 16.00, durationSteps = 16.00, velocity = 0.85, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
              },
            },
          },
        },
      }
    },
    {
      id = "p1",
      name = "Pattern B",
      lengthSteps = 32,
      tracks = {
        {
          id = "p1_k",
          name = "Eats Kick",
          color = 0xffff007a,
          type = "luaScript",
          volume = 0.950,
          pan = 0.000,
          isMuted = false,
          isSoloed = false,
          chordFollowMode = "off",
          sampleName = "kick",
          synthWaveform = "sawtooth",
          cutoff = 3000.0,
          resonance = 1.00,
          attack = 0.010,
          release = 0.300,
          trackerColumns = 4,
          activeView = "pianoRoll",
          luaScriptCode = [[
-- --- Procedural Sub Kick Drum Script (Lua) ---
local ProceduralKick = {}

function ProceduralKick.init()
  Param.add("StartFreq", 100.0, 300.0, 160.0)
  Param.add("EndFreq", 30.0, 60.0, 42.0)
  Param.add("PitchDecay", 0.01, 0.1, 0.035)
  Param.add("AmpDecay", 0.1, 0.6, 0.35)
  Param.add("Click", 0.0, 1.0, 0.0)
end

function ProceduralKick.process(time, freq, note, params)
  local startF = params["StartFreq"] or 160.0
  local endF = params["EndFreq"] or 42.0
  local pDecay = params["PitchDecay"] or 0.035
  local aDecay = params["AmpDecay"] or 0.35
  local click = params["Click"] or 0.0

  -- Pitch sweep envelope
  local curFreq = endF + (startF - endF) * math.exp(-time / math.max(0.005, pDecay))
  local phase = 2.0 * math.pi * curFreq * time
  local subSine = math.sin(phase)

  -- Transient click
  local clickTransient = (math.random() * 2.0 - 1.0) * math.exp(-time * 150.0) * click

  -- Amplitude envelope decaying to near zero by time = aDecay
  local env = math.exp(-time * 5.0 / math.max(0.01, aDecay))
  local rawOutput = (subSine * 0.85 + clickTransient * 0.15) * env

  -- Smooth fade toward edge of kick duration to guarantee clean drop to silence
  local maxDur = math.max(0.1, aDecay)
  local fadeStart = maxDur - 0.04
  local edgeFade = 1.0
  if time > fadeStart then
    local norm = math.max(0.0, math.min(1.0, (maxDur - time) / 0.04))
    edgeFade = 0.5 * (1.0 - math.cos(math.pi * norm))
  end
  if time >= maxDur then edgeFade = 0.0 end
  return math.tanh(rawOutput * edgeFade * 1.3)
end

return ProceduralKick
          ]],
          luaParams = {
            ["StartFreq"] = 160.0000,
            ["EndFreq"] = 42.0000,
            ["PitchDecay"] = 0.0350,
            ["AmpDecay"] = 0.3500,
            ["Click"] = 0.0000,
          },
          steps = {
            [1] = { pitch = 36, velocity = 0.95, isSlide = false, isAccent = true },
            [2] = { pitch = 36, velocity = 0.95, isSlide = false, isAccent = true },
            [3] = { pitch = 36, velocity = 0.95, isSlide = false, isAccent = true },
            [4] = { pitch = 36, velocity = 0.95, isSlide = false, isAccent = true },
            [5] = { pitch = 36, velocity = 0.95, isSlide = false, isAccent = true },
            [6] = { pitch = 36, velocity = 0.95, isSlide = false, isAccent = true },
            [7] = { pitch = 36, velocity = 0.95, isSlide = false, isAccent = true },
            [8] = { pitch = 36, velocity = 0.95, isSlide = false, isAccent = true },
          },
          notes = {
            { id = "k_0", pitch = 36, startStep = 0.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "k_4", pitch = 36, startStep = 4.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "k_8", pitch = 36, startStep = 8.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "k_12", pitch = 36, startStep = 12.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "k_16", pitch = 36, startStep = 16.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "k_20", pitch = 36, startStep = 20.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "k_24", pitch = 36, startStep = 24.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "k_28", pitch = 36, startStep = 28.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
          },
          clips = {
            {
              id = "c_k1",
              name = "Kick Beat A",
              trackId = "t_kick",
              startBar = 0,
              barLength = 4,
              notes = {
                { id = "k_0", pitch = 36, startStep = 0.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "k_4", pitch = 36, startStep = 4.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "k_8", pitch = 36, startStep = 8.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "k_12", pitch = 36, startStep = 12.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "k_16", pitch = 36, startStep = 16.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "k_20", pitch = 36, startStep = 20.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "k_24", pitch = 36, startStep = 24.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "k_28", pitch = 36, startStep = 28.00, durationSteps = 1.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
              },
            },
          },
        },
        {
          id = "p1_s",
          name = "Eats Snare",
          color = 0xffff8c00,
          type = "luaScript",
          volume = 0.850,
          pan = 0.000,
          isMuted = false,
          isSoloed = false,
          chordFollowMode = "off",
          sampleName = "kick",
          synthWaveform = "sawtooth",
          cutoff = 3000.0,
          resonance = 1.00,
          attack = 0.010,
          release = 0.300,
          trackerColumns = 4,
          activeView = "pianoRoll",
          luaScriptCode = [[
-- --- Procedural Snare Drum Script (Lua) ---
local ProceduralSnare = {}

function ProceduralSnare.init()
  Param.add("ToneFreq", 100.0, 300.0, 185.0)
  Param.add("Snappy", 0.0, 1.0, 0.65)
  Param.add("Decay", 0.05, 0.5, 0.1)
end

function ProceduralSnare.process(time, freq, note, params)
  local toneFreq = params["ToneFreq"] or 185.0
  local snappy = params["Snappy"] or 0.65
  local decay = params["Decay"] or 0.1

  -- Body tone (pitch sweep)
  local sweepFreq = toneFreq * math.exp(-time * 40.0)
  local body = math.sin(2.0 * math.pi * sweepFreq * time) * math.exp(-time * 25.0)

  -- Snare noise wires
  local noise = (math.random() * 2.0 - 1.0) * math.exp(-time / decay)
  local filteredNoise = DSP.highpass(noise, 1500.0, 1.0)

  local output = body * (1.0 - snappy) + filteredNoise * snappy
  return math.tanh(output * 1.2)
end

return ProceduralSnare
          ]],
          luaParams = {
            ["ToneFreq"] = 185.0000,
            ["Snappy"] = 0.6500,
            ["Decay"] = 0.1000,
          },
          steps = {
            [1] = { pitch = 38, velocity = 0.90, isSlide = false, isAccent = true },
            [2] = { pitch = 38, velocity = 0.90, isSlide = false, isAccent = true },
            [3] = { pitch = 38, velocity = 0.90, isSlide = false, isAccent = true },
            [4] = { pitch = 38, velocity = 0.90, isSlide = false, isAccent = true },
          },
          notes = {
            { id = "s_4", pitch = 38, startStep = 4.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "s_12", pitch = 38, startStep = 12.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "s_20", pitch = 38, startStep = 20.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "s_28", pitch = 38, startStep = 28.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
          },
          clips = {
            {
              id = "c_s1",
              name = "Snare Pattern",
              trackId = "t_snare",
              startBar = 0,
              barLength = 4,
              notes = {
                { id = "s_4", pitch = 38, startStep = 4.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "s_12", pitch = 38, startStep = 12.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "s_20", pitch = 38, startStep = 20.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "s_28", pitch = 38, startStep = 28.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
              },
            },
          },
        },
        {
          id = "p1_h",
          name = "Eats Hats",
          color = 0xffffb700,
          type = "luaScript",
          volume = 0.750,
          pan = 0.000,
          isMuted = false,
          isSoloed = false,
          chordFollowMode = "off",
          sampleName = "kick",
          synthWaveform = "sawtooth",
          cutoff = 3000.0,
          resonance = 1.00,
          attack = 0.010,
          release = 0.300,
          trackerColumns = 4,
          activeView = "pianoRoll",
          luaScriptCode = [[
-- --- Procedural Hi-Hat Synth Script (Lua) ---
local ProceduralHiHat = {}

function ProceduralHiHat.init()
  Param.add("Cutoff", 4000.0, 14000.0, 8500.0)
  Param.add("Decay", 0.01, 0.4, 0.05)
  Param.add("Metallic", 0.0, 1.0, 0.15)
end

function ProceduralHiHat.process(time, freq, note, params)
  local cutoff = params["Cutoff"] or 8500.0
  local decay = params["Decay"] or 0.05
  local metallic = params["Metallic"] or 0.15

  local env = math.exp(-time / math.max(0.005, decay))

  -- Metallic ring harmonics (6 detuned square waves for TR-style metallic sheen)
  local ring1 = math.sin(2.0 * math.pi * 205.0 * time) > 0 and 1.0 or -1.0
  local ring2 = math.sin(2.0 * math.pi * 305.0 * time) > 0 and 1.0 or -1.0
  local ring3 = math.sin(2.0 * math.pi * 365.0 * time) > 0 and 1.0 or -1.0
  local ring4 = math.sin(2.0 * math.pi * 396.0 * time) > 0 and 1.0 or -1.0
  local ring5 = math.sin(2.0 * math.pi * 434.0 * time) > 0 and 1.0 or -1.0
  local ring6 = math.sin(2.0 * math.pi * 700.0 * time) > 0 and 1.0 or -1.0
  local metallicRing = (ring1 + ring2 + ring3 + ring4 + ring5 + ring6) / 6.0

  -- White noise generator (primary hi-hat sound source)
  local noise = (math.random() * 2.0 - 1.0)
  local rawSignal = noise * (1.0 - metallic * 0.4) + metallicRing * (metallic * 0.4)

  -- High-pass filtered noise sibilance
  local filtered = DSP.highpass(rawSignal, cutoff, 1.2)

  return filtered * env * 0.75
end

return ProceduralHiHat
          ]],
          luaParams = {
            ["Cutoff"] = 8500.0000,
            ["Decay"] = 0.0500,
            ["Metallic"] = 0.1500,
          },
          steps = {
            [1] = { pitch = 42, velocity = 0.60, isSlide = false, isAccent = false },
            [2] = { pitch = 42, velocity = 0.90, isSlide = false, isAccent = true },
            [3] = { pitch = 42, velocity = 0.60, isSlide = false, isAccent = false },
            [4] = { pitch = 42, velocity = 0.90, isSlide = false, isAccent = true },
            [5] = { pitch = 42, velocity = 0.60, isSlide = false, isAccent = false },
            [6] = { pitch = 42, velocity = 0.90, isSlide = false, isAccent = true },
            [7] = { pitch = 42, velocity = 0.60, isSlide = false, isAccent = false },
            [8] = { pitch = 42, velocity = 0.90, isSlide = false, isAccent = true },
            [9] = { pitch = 42, velocity = 0.60, isSlide = false, isAccent = false },
            [10] = { pitch = 42, velocity = 0.90, isSlide = false, isAccent = true },
            [11] = { pitch = 42, velocity = 0.60, isSlide = false, isAccent = false },
            [12] = { pitch = 42, velocity = 0.90, isSlide = false, isAccent = true },
            [13] = { pitch = 42, velocity = 0.60, isSlide = false, isAccent = false },
            [14] = { pitch = 42, velocity = 0.90, isSlide = false, isAccent = true },
            [15] = { pitch = 42, velocity = 0.60, isSlide = false, isAccent = false },
            [16] = { pitch = 42, velocity = 0.90, isSlide = false, isAccent = true },
          },
          notes = {
            { id = "h_0", pitch = 42, startStep = 0.00, durationSteps = 1.00, velocity = 0.60, column = 0, effectCommand = "00", isSlide = false, isAccent = false },
            { id = "h_2", pitch = 42, startStep = 2.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "h_4", pitch = 42, startStep = 4.00, durationSteps = 1.00, velocity = 0.60, column = 0, effectCommand = "00", isSlide = false, isAccent = false },
            { id = "h_6", pitch = 42, startStep = 6.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "h_8", pitch = 42, startStep = 8.00, durationSteps = 1.00, velocity = 0.60, column = 0, effectCommand = "00", isSlide = false, isAccent = false },
            { id = "h_10", pitch = 42, startStep = 10.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "h_12", pitch = 42, startStep = 12.00, durationSteps = 1.00, velocity = 0.60, column = 0, effectCommand = "00", isSlide = false, isAccent = false },
            { id = "h_14", pitch = 42, startStep = 14.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "h_16", pitch = 42, startStep = 16.00, durationSteps = 1.00, velocity = 0.60, column = 0, effectCommand = "00", isSlide = false, isAccent = false },
            { id = "h_18", pitch = 42, startStep = 18.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "h_20", pitch = 42, startStep = 20.00, durationSteps = 1.00, velocity = 0.60, column = 0, effectCommand = "00", isSlide = false, isAccent = false },
            { id = "h_22", pitch = 42, startStep = 22.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = false },
          },
          clips = {
            {
              id = "clip_p1_h_0",
              name = "Eats Hats Clip",
              trackId = "p1_h",
              startBar = 0,
              barLength = 2,
              luaScriptCode = [[
-- --- Procedural Hi-Hat Synth Script (Lua) ---
local ProceduralHiHat = {}

function ProceduralHiHat.init()
  Param.add("Cutoff", 4000.0, 14000.0, 8500.0)
  Param.add("Decay", 0.01, 0.4, 0.05)
  Param.add("Metallic", 0.0, 1.0, 0.15)
end

function ProceduralHiHat.process(time, freq, note, params)
  local cutoff = params["Cutoff"] or 8500.0
  local decay = params["Decay"] or 0.05
  local metallic = params["Metallic"] or 0.15

  local env = math.exp(-time / math.max(0.005, decay))

  -- Metallic ring harmonics (6 detuned square waves for TR-style metallic sheen)
  local ring1 = math.sin(2.0 * math.pi * 205.0 * time) > 0 and 1.0 or -1.0
  local ring2 = math.sin(2.0 * math.pi * 305.0 * time) > 0 and 1.0 or -1.0
  local ring3 = math.sin(2.0 * math.pi * 365.0 * time) > 0 and 1.0 or -1.0
  local ring4 = math.sin(2.0 * math.pi * 396.0 * time) > 0 and 1.0 or -1.0
  local ring5 = math.sin(2.0 * math.pi * 434.0 * time) > 0 and 1.0 or -1.0
  local ring6 = math.sin(2.0 * math.pi * 700.0 * time) > 0 and 1.0 or -1.0
  local metallicRing = (ring1 + ring2 + ring3 + ring4 + ring5 + ring6) / 6.0

  -- White noise generator (primary hi-hat sound source)
  local noise = (math.random() * 2.0 - 1.0)
  local rawSignal = noise * (1.0 - metallic * 0.4) + metallicRing * (metallic * 0.4)

  -- High-pass filtered noise sibilance
  local filtered = DSP.highpass(rawSignal, cutoff, 1.2)

  return filtered * env * 0.75
end

return ProceduralHiHat
              ]],
              luaParams = { ["Cutoff"] = 8500.0000, ["Decay"] = 0.0500, ["Metallic"] = 0.1500 },
              notes = {
                { id = "h_0", pitch = 42, startStep = 0.00, durationSteps = 1.00, velocity = 0.60, column = 0, effectCommand = "00", isSlide = false, isAccent = false },
                { id = "h_2", pitch = 42, startStep = 2.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "h_4", pitch = 42, startStep = 4.00, durationSteps = 1.00, velocity = 0.60, column = 0, effectCommand = "00", isSlide = false, isAccent = false },
                { id = "h_6", pitch = 42, startStep = 6.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "h_8", pitch = 42, startStep = 8.00, durationSteps = 1.00, velocity = 0.60, column = 0, effectCommand = "00", isSlide = false, isAccent = false },
                { id = "h_10", pitch = 42, startStep = 10.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "h_12", pitch = 42, startStep = 12.00, durationSteps = 1.00, velocity = 0.60, column = 0, effectCommand = "00", isSlide = false, isAccent = false },
                { id = "h_14", pitch = 42, startStep = 14.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "h_16", pitch = 42, startStep = 16.00, durationSteps = 1.00, velocity = 0.60, column = 0, effectCommand = "00", isSlide = false, isAccent = false },
                { id = "h_18", pitch = 42, startStep = 18.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "h_20", pitch = 42, startStep = 20.00, durationSteps = 1.00, velocity = 0.60, column = 0, effectCommand = "00", isSlide = false, isAccent = false },
                { id = "h_22", pitch = 42, startStep = 22.00, durationSteps = 1.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = false },
              },
            },
          },
        },
        {
          id = "p1_w",
          name = "Eats 303",
          color = 0xff00ff66,
          type = "luaScript",
          volume = 0.900,
          pan = 0.000,
          isMuted = false,
          isSoloed = false,
          chordFollowMode = "off",
          sampleName = "kick",
          synthWaveform = "sawtooth",
          cutoff = 3000.0,
          resonance = 1.00,
          attack = 0.010,
          release = 0.300,
          trackerColumns = 4,
          activeView = "pianoRoll",
          luaScriptCode = [[
-- --- JC-303 Roland TB-303 Acid Engine (Lua) ---
local Acid303 = {}

function Acid303.init()
  Param.add("Waveform", 0.0, 1.0, 0.0)    -- 0 = Saw, 1 = Square
  Param.add("Cutoff", 100.0, 6500.0, 1600.0)
  Param.add("Resonance", 0.5, 16.0, 8.0)
  Param.add("EnvMod", 0.0, 1.0, 0.75)
  Param.add("Decay", 0.05, 1.2, 0.28)
  Param.add("Accent", 0.0, 1.0, 0.6)
  Param.add("Slide", 0.0, 1.0, 0.4)
  Param.add("Overdrive", 0.0, 1.0, 0.3)
end

function Acid303.process(time, freq, note, params, targetNote, isSlide, isAccent)
  local waveType = params["Waveform"] or 0.0
  local cutoff = params["Cutoff"] or 1600.0
  local res = params["Resonance"] or 8.0
  local envMod = params["EnvMod"] or 0.75
  local decay = params["Decay"] or 0.28
  local accent = params["Accent"] or 0.6
  local drive = params["Overdrive"] or 0.3
  local slideParam = params["Slide"] or 0.4

  -- Pitch glide / Portamento logic for JC-303 continuous monophonic voice
  local currentFreq = freq
  if targetNote and targetNote > 0 then
    local targetFreq = 440.0 * (2.0 ^ ((targetNote - 69) / 12.0))
    currentFreq = targetFreq + (freq - targetFreq) * math.exp(-time / 0.060)
  elseif isSlide or slideParam > 0.5 then
    local targetFreq = targetNote and (440.0 * (2.0 ^ ((targetNote - 69) / 12.0))) or freq
    currentFreq = targetFreq + (freq - targetFreq) * math.exp(-time / 0.060)
  end

  -- JC-303 Oscillators: Leaky Integrator Sawtooth & Differentiated Square
  local phase = time * currentFreq
  local normPhase = phase - math.floor(phase)
  local sawRaw = 2.0 * normPhase - 1.0
  local sawHP = sawRaw - 0.85 * math.exp(-time * 12.0)
  local sqrRaw = normPhase < 0.46 and 0.75 or -0.75
  local osc = waveType < 0.5 and sawHP or sqrRaw

  -- Dynamic Accent & VCF Envelope Decay Dynamics
  local hasAccent = isAccent or (accent > 0.7 and not isSlide)
  local envBoost = hasAccent and (1.0 + accent * 1.1) or 1.0
  local envDecay = decay / (hasAccent and (1.0 + accent * 0.9) or 1.0)
  local env = math.exp(-time / envDecay)
  local accentPulse = hasAccent and (accent * 0.4 * math.exp(-time / 0.035)) or 0.0

  -- 24dB 4-Pole Diode Ladder Filter simulation with feedback saturation
  local modCutoff = cutoff + (envMod * (env + accentPulse) * 6500.0 * envBoost)
  local filtered = DSP.lowpass(osc, modCutoff, res)

  -- Post-VCF 150Hz 1-Pole High-Pass filter & overdrive saturation
  local highpassed = filtered * 0.98
  local output = highpassed * (hasAccent and 1.35 or 1.0)
  if drive > 0.05 then
    output = math.tanh(output * (1.0 + drive * 4.0))
  end

  return output
end

return Acid303
          ]],
          luaParams = {
            ["Waveform"] = 0.0000,
            ["Cutoff"] = 1800.0000,
            ["Resonance"] = 8.0000,
            ["EnvMod"] = 0.7500,
            ["Decay"] = 0.2800,
            ["Accent"] = 0.6000,
            ["Slide"] = 0.4000,
            ["Overdrive"] = 0.3000,
          },
          steps = {
            [1] = { pitch = 36, velocity = 0.85, isSlide = false, isAccent = true },
            [2] = { pitch = 42, velocity = 0.85, isSlide = false, isAccent = true },
            [3] = { pitch = 36, velocity = 0.85, isSlide = false, isAccent = true },
            [4] = { pitch = 42, velocity = 0.85, isSlide = false, isAccent = true },
            [5] = { pitch = 36, velocity = 0.85, isSlide = false, isAccent = true },
            [6] = { pitch = 42, velocity = 0.85, isSlide = false, isAccent = true },
            [7] = { pitch = 36, velocity = 0.85, isSlide = false, isAccent = true },
            [8] = { pitch = 42, velocity = 0.85, isSlide = false, isAccent = true },
            [9] = { pitch = 36, velocity = 0.85, isSlide = false, isAccent = true },
            [10] = { pitch = 42, velocity = 0.85, isSlide = false, isAccent = true },
            [11] = { pitch = 36, velocity = 0.85, isSlide = false, isAccent = true },
            [12] = { pitch = 42, velocity = 0.85, isSlide = false, isAccent = true },
            [13] = { pitch = 36, velocity = 0.85, isSlide = false, isAccent = true },
            [14] = { pitch = 42, velocity = 0.85, isSlide = false, isAccent = true },
            [15] = { pitch = 36, velocity = 0.85, isSlide = false, isAccent = true },
            [16] = { pitch = 42, velocity = 0.85, isSlide = false, isAccent = true },
          },
          notes = {
            { id = "n1", pitch = 36, startStep = 0.00, durationSteps = 2.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "n2", pitch = 36, startStep = 2.00, durationSteps = 1.00, velocity = 0.80, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "n3", pitch = 48, startStep = 3.00, durationSteps = 1.00, velocity = 1.00, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "n4", pitch = 39, startStep = 4.00, durationSteps = 2.00, velocity = 0.85, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "n5", pitch = 41, startStep = 6.00, durationSteps = 2.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "n6", pitch = 43, startStep = 8.00, durationSteps = 2.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "n7", pitch = 36, startStep = 10.00, durationSteps = 2.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "n8", pitch = 48, startStep = 12.00, durationSteps = 2.00, velocity = 1.00, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
            { id = "n9", pitch = 46, startStep = 14.00, durationSteps = 2.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
          },
          clips = {
            {
              id = "c_w1",
              name = "Acid 303 Riff",
              trackId = "t_lua_303",
              startBar = 0,
              barLength = 4,
              notes = {
                { id = "n1", pitch = 36, startStep = 0.00, durationSteps = 2.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "n2", pitch = 36, startStep = 2.00, durationSteps = 1.00, velocity = 0.80, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "n3", pitch = 48, startStep = 3.00, durationSteps = 1.00, velocity = 1.00, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "n4", pitch = 39, startStep = 4.00, durationSteps = 2.00, velocity = 0.85, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "n5", pitch = 41, startStep = 6.00, durationSteps = 2.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "n6", pitch = 43, startStep = 8.00, durationSteps = 2.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "n7", pitch = 36, startStep = 10.00, durationSteps = 2.00, velocity = 0.95, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "n8", pitch = 48, startStep = 12.00, durationSteps = 2.00, velocity = 1.00, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
                { id = "n9", pitch = 46, startStep = 14.00, durationSteps = 2.00, velocity = 0.90, column = 0, effectCommand = "00", isSlide = false, isAccent = true },
              },
            },
          },
        },
      }
    },
  },

  arranger = {
    activePatternIndex = 0,
    items = {
      { patternId = "p0", startBar = 0, barLength = 4 },
      { patternId = "p1", startBar = 4, barLength = 4 },
    }
  },

  chordTrack = {
    { id = "chord_1787689858568_0", startBar = 0, barLength = 1.0, rootPitchClass = 0, quality = "major" },
    { id = "chord_1787689858568_1", startBar = 1, barLength = 1.0, rootPitchClass = 7, quality = "major" },
    { id = "chord_1787689858568_2", startBar = 2, barLength = 1.0, rootPitchClass = 9, quality = "minor" },
    { id = "chord_1787689858568_3", startBar = 3, barLength = 1.0, rootPitchClass = 5, quality = "major" },
    { id = "chord_1787689794785_4", startBar = 4, barLength = 1.0, rootPitchClass = 5, quality = "major" },
  },

  masterFx = {
    { id = "fx_1788123450285_convolutionReverb", name = "Room Designer", type = "convolutionReverb", enabled = true, mix = 0.50, params = { ["DryLevel"] = 1.0000, ["WetLevel"] = 0.5000, ["PreDelayMs"] = 10.0000, ["HighCut"] = 8000.0000, ["Width"] = 15.0000, ["Length"] = 25.0000, ["Height"] = 10.0000, ["Material"] = 0.0000, ["RT60"] = 2.2000, ["Damping"] = 0.2500, ["SourceX"] = 0.5000, ["SourceY"] = 0.5000, ["SourceZ"] = 0.5000, ["ListenerX"] = 0.5000, ["ListenerY"] = 0.8000, ["ListenerZ"] = 0.5000, ["StereoWidth"] = 0.2000 }, irSampleName = "Room: Master_fx_1788123450285_convolutionReverb", presetId = "room_designer", luaScriptCode = [[
-- @name: Room Designer
-- @category: audioFx
-- @description: Interactive 3D Room Acoustic Synthesizer with Image Source & Velvet Noise physics
local RoomDesigner = {}

function RoomDesigner.init()
  Param.add("Width", 1.0, 30.0, 15.0, 0.5)
  Param.add("Length", 1.0, 40.0, 25.0, 0.5)
  Param.add("Height", 1.0, 18.0, 10.0, 0.5)
  Param.choice("Material", {"Wood Paneling", "Pine Wood", "Acoustic Foam", "Hard Concrete", "Birch Plywood", "Velvet Drapes", "Sheet Metal", "Carpet"}, 0.0)
  Param.add("RT60", 0.1, 5.0, 2.2, 0.05)
  Param.add("Damping", 0.0, 1.0, 0.25, 0.05)
  Param.add("SourceX", 0.05, 0.95, 0.50, 0.01)
  Param.add("SourceY", 0.05, 0.95, 0.50, 0.01)
  Param.add("SourceZ", 0.05, 0.95, 0.50, 0.01)
  Param.add("ListenerX", 0.05, 0.95, 0.50, 0.01)
  Param.add("ListenerY", 0.05, 0.95, 0.80, 0.01)
  Param.add("ListenerZ", 0.05, 0.95, 0.50, 0.01)
  Param.add("StereoWidth", 0.05, 1.00, 0.20, 0.01)
  Param.add("DryLevel", 0.0, 1.5, 1.0, 0.05)
  Param.add("WetLevel", 0.0, 1.5, 0.5, 0.05)
end

function RoomDesigner.process(input_l, input_r, params)
  return input_l, input_r
end

function RoomDesigner.gui()
  return {
    panel = {
      title = "Room Designer",
      subtitle = "3D Image Source & Velvet Noise Acoustic Engine",
      background = "grunge",
      accent = "#21F4E8",
      layout = {
        { type = "space_visualizer", height = 135 },
        {
          type = "row",
          children = {
            { type = "listbox", param = "Material", label = "MATERIAL", width = 130, height = 70 },
            { type = "knob", param = "Width", label = "WIDTH", unit = "m" },
            { type = "knob", param = "Length", label = "LENGTH", unit = "m" },
            { type = "knob", param = "Height", label = "HEIGHT", unit = "m" },
            { type = "knob", param = "RT60", label = "DECAY", unit = "s" },
            { type = "knob", param = "Damping", label = "DAMP" },
          }
        },
        {
          type = "row",
          children = {
            { type = "knob", param = "SourceX", label = "SRC X", size = 36 },
            { type = "knob", param = "SourceY", label = "SRC Y", size = 36 },
            { type = "knob", param = "SourceZ", label = "SRC Z", size = 36 },
            { type = "knob", param = "ListenerX", label = "MIC X", size = 36 },
            { type = "knob", param = "ListenerY", label = "MIC Y", size = 36 },
            { type = "knob", param = "ListenerZ", label = "MIC Z", size = 36 },
            { type = "knob", param = "StereoWidth", label = "SPREAD", unit = "m", size = 36 },
          }
        },
        {
          type = "row",
          children = {
            { type = "hslider", param = "DryLevel", label = "DRY LEVEL", width = 480, style = "capsule" },
          }
        },
        {
          type = "row",
          children = {
            { type = "hslider", param = "WetLevel", label = "WET LEVEL", width = 480, style = "capsule" },
          }
        }
      }
    }
  }
end

function RoomDesigner.rack()
  return {
    rows = {
      {
        { id = "in_lr",     title = "AUDIO INPUT L/R", hp = 14, row = 1, category = "OUT" },
        { id = "early_ref", title = "3D IMAGE SOURCE CORE", hp = 16, row = 1, category = "FX" },
      },
      {
        { id = "velvet_tail", title = "VELVET NOISE LATE TAIL", hp = 16, row = 2, category = "FX" },
        { id = "out_lr",      title = "ACOUSTIC ROOM OUT", hp = 14, row = 2, category = "OUT" },
      },
    },
    cables = {
      { from = "1:0:1", to = "1:1:0", color = "audio" },
      { from = "1:1:1", to = "2:0:0", color = "audio" },
      { from = "2:0:1", to = "2:1:0", color = "audio" },
    }
  }
end

return RoomDesigner
  ]], luaParams = { ["Width"] = 15.0000, ["Length"] = 25.0000, ["Height"] = 10.0000, ["Material"] = 0.0000, ["RT60"] = 2.2000, ["Damping"] = 0.2500, ["SourceX"] = 0.5000, ["SourceY"] = 0.5000, ["SourceZ"] = 0.5000, ["ListenerX"] = 0.5000, ["ListenerY"] = 0.8000, ["ListenerZ"] = 0.5000, ["StereoWidth"] = 0.2000, ["DryLevel"] = 1.0000, ["WetLevel"] = 0.5000 } },
  },
}
